// swift-tools-version:5.9
import PackageDescription

// Sources are kept here in a flat list so the generator script and downstream
// scripts can edit them mechanically. Each entry is a path relative to
// Sources/HSExtensions/. Extension directories are symlinked into that folder
// so the source-of-truth remains under extensions/<name>/.
let extensionSourcePaths: [String] = [
    "HSExtensions.m",
    "application/libapplication.m",
    "application/libapplication_watcher.m",
    "audiodevice/libaudiodevice.m",
    "audiodevice/libaudiodevice_watcher.m",
    "axuielement/axtextmarker.m",
    "axuielement/common.m",
    "axuielement/libaxuielement.m",
    "axuielement/observer.m",
    "base64/libbase64.m",
    "battery/libbattery.m",
    "battery/libbattery_watcher.m",
    "bonjour/libbonjoir.m",
    "bonjour/libbonjour_service.m",
    "brightness/libbrightness.m",
    "caffeinate/libcaffeinate.m",
    "caffeinate/libcaffeinate_watcher.m",
    "camera/libcamera.m",
    "canvas/imageAdditions.m",
    "canvas/libcanvas.m",
    "canvas/libcanvas_matrix.m",
    "chooser/HSChooser.m",
    "chooser/HSChooserCell.m",
    "chooser/HSChooserRootView.m",
    "chooser/HSChooserTableView.m",
    "chooser/HSChooserVerticallyCenteringTextFieldCell.m",
    "chooser/HSChooserWindow.m",
    "chooser/libchooser.m",
    "console/libconsole.m",
    "crash/libcrash.m",
    "dialog/libdialog.m",
    "distributednotifications/libdistributednotifications.m",
    "doc/autolink.c",
    "doc/buffer.c",
    "doc/houdini_href_e.c",
    "doc/houdini_html_e.c",
    "doc/html.c",
    "doc/libdoc.m",
    "doc/markdown.c",
    "doc/markdown.m",
    "doc/plaintext.c",
    "doc/stack.c",
    "dockicon/libdockicon.m",
    "drawing/color/libdrawing_color.m",
    "eventtap/TouchEvents.c",
    "eventtap/libeventtap.m",
    "eventtap/libeventtap_event.m",
    "fs/libfs.m",
    "fs/libfs_volume.m",
    "fs/libfs_xattr.m",
    "hash/algorithms.m",
    "hash/libhash.m",
    "hash/sha3.m",
    "hid/led.m",
    "hid/libhid.m",
    "hints/internal.m",
    "host/libhost.m",
    "host/locale/libhost_locale.m",
    "hotkey/libhotkey.m",
    "http/libhttp.m",
    "httpserver/MYAnonymousIdentity.m",
    "httpserver/libhttpserver.m",
    "image/libimage.m",
    "ipc/libipc.m",
    "json/libjson.m",
    "keycodes/libkeycodes.m",
    "location/EDSunriseSet.m",
    "location/liblocation.m",
    "math/libmath.m",
    "menubar/libmenubar.m",
    "midi/libmidi.m",
    "milight/libmilight.m",
    "mouse/libmouse.m",
    "network/libnetwork_configuration.m",
    "network/libnetwork_host.m",
    "network/libnetwork_reachability.m",
    "network/ping/SimplePing.m",
    "network/ping/libnetwork_ping.m",
    "noises/detectors.cpp",
    "noises/libnoises.m",
    "notify/libnotify.m",
    "osascript/NSAppleEventDescriptor+Parsing.m",
    "osascript/libosascript.m",
    "pasteboard/libpasteboard.m",
    "pasteboard/libpasteboard_watcher.m",
    "pathwatcher/libpathwatcher.m",
    "plist/libplist.m",
    "razer/HSRazerDevice.m",
    "razer/HSRazerManager.m",
    "razer/HSRazerTartarusV2Device.m",
    "razer/librazer.m",
    "screen/libscreen.m",
    "screen/libscreen_watcher.m",
    "serial/libserial.m",
    "settings/libsettings.m",
    "sharing/libsharing.m",
    "shortcuts/libshortcuts.m",
    "socket/libsocket.m",
    "socket/libsocket_udp.m",
    "sound/libsound.m",
    "spaces/libspaces.m",
    "spaces/libspaces_watcher.m",
    "speech/libspeech.m",
    "speech/libspeech_listener.m",
    "spotlight/libspotlight.m",
    "lsqlite3_wrapper.m",  // includes sqlite3/lsqlite3.c as Objective-C
    "streamdeck/HSStreamDeckDevice.m",
    "streamdeck/HSStreamDeckDeviceMini.m",
    "streamdeck/HSStreamDeckDeviceMk2.m",
    "streamdeck/HSStreamDeckDeviceOriginal.m",
    "streamdeck/HSStreamDeckDeviceOriginalV2.m",
    "streamdeck/HSStreamDeckDevicePedal.m",
    "streamdeck/HSStreamDeckDevicePlus.m",
    "streamdeck/HSStreamDeckDeviceXL.m",
    "streamdeck/HSStreamDeckManager.m",
    "streamdeck/NSImage+BMP.m",
    "streamdeck/NSImage+Flipped.m",
    "streamdeck/NSImage+JPEG.m",
    "streamdeck/NSImage+Rotated.m",
    "streamdeck/libstreamdeck.m",
    "styledtext/libstyledtext.m",
    "task/libtask.m",
    "timer/libtimer.m",
    "uielement/libuielement.m",
    "uielement/libuielement_watcher.m",
    "urlevent/liburlevent.m",
    "usb/libusb.m",
    "usb/libusb_watcher.m",
    "websocket/libwebsocket.m",
    "webview/libwebview.m",
    "webview/libwebview_datastore.m",
    "webview/libwebview_toolbar.m",
    "webview/libwebview_usercontent.m",
    "wifi/libwifi.m",
    "wifi/libwifi_watcher.m",
    "window/libwindow.m",
]

let package = Package(
    name: "HSExtensions",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "HSExtensions", type: .static, targets: ["HSExtensions"]),
    ],
    dependencies: [
        .package(path: "../LuaSkin"),
        .package(path: "../CocoaHTTPServer"),
        .package(url: "https://github.com/robbiehanson/CocoaAsyncSocket", exact: "7.6.5"),
        .package(url: "https://github.com/armadsen/ORSSerialPort", exact: "2.1.0"),
        .package(url: "https://github.com/CocoaLumberjack/CocoaLumberjack", exact: "3.8.5"),
    ],
    targets: [
        .target(
            name: "HSExtensions",
            dependencies: [
                "LuaSkin",
                "CocoaHTTPServer",
                "CocoaAsyncSocket",
                .product(name: "ORSSerial", package: "ORSSerialPort"),
                .product(name: "CocoaLumberjack", package: "CocoaLumberjack"),
            ],
            path: "Sources/HSExtensions",
            sources: extensionSourcePaths,
            publicHeadersPath: "include",
            cSettings: [
                .define("LUA_USE_MACOSX"),
                .define("LUA_COMPAT_5_3"),
                // Header search paths so #import "Foo.h" resolves for extensions
                // that include sibling files relatively or that share helper
                // headers under the main app source tree.
                .headerSearchPath("Hammerspoon"),
                .headerSearchPath("axuielement"),
                .headerSearchPath("canvas"),
                .headerSearchPath("chooser"),
                .headerSearchPath("doc"),
                .headerSearchPath("eventtap"),
                .headerSearchPath("fs"),
                .headerSearchPath("hash"),
                .headerSearchPath("hid"),
                .headerSearchPath("httpserver"),
                .headerSearchPath("location"),
                .headerSearchPath("network/ping"),
                .headerSearchPath("noises"),
                .headerSearchPath("osascript"),
                .headerSearchPath("razer"),
                .headerSearchPath("shortcuts"),
                .headerSearchPath("socket"),
                .headerSearchPath("spaces"),
                .headerSearchPath("streamdeck"),
                .headerSearchPath("webview"),
                .unsafeFlags([
                    "-Wno-everything",
                ]),
            ],
            cxxSettings: [
                .define("LUA_USE_MACOSX"),
            ],
            linkerSettings: [
                .linkedFramework("Cocoa"),
                .linkedFramework("Foundation"),
                .linkedFramework("AppKit"),
                .linkedFramework("Carbon"),
                .linkedFramework("IOKit"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("CoreServices"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("Quartz"),
                .linkedFramework("ApplicationServices"),
                .linkedFramework("Accelerate"),
                .linkedFramework("AVFoundation"),
                .linkedFramework("AVKit"),
                .linkedFramework("WebKit"),
                .linkedFramework("Vision"),
                .linkedFramework("CoreMIDI"),
                .linkedFramework("CoreLocation"),
                .linkedFramework("CoreWLAN"),
                .linkedFramework("CoreSpotlight"),
                .linkedFramework("CoreBluetooth"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("DiscRecording"),
                .linkedFramework("ImageCaptureCore"),
                .linkedFramework("MediaPlayer"),
                .linkedFramework("ScreenCaptureKit"),
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("Security"),
                .linkedFramework("Intents"),
                .linkedFramework("UserNotifications"),
                .linkedFramework("ServiceManagement"),
                .linkedFramework("OSAKit"),
                .linkedFramework("ScriptingBridge"),
                .linkedFramework("IOBluetooth"),
                .linkedLibrary("sqlite3"),
                .linkedLibrary("z"),
            ]
        ),
    ]
)
