import Cocoa
import CLua
import HSDSTCore
import Lua
import os.log

private let USERDATA_TAG = "hs.dialog"

// MARK: - Support Functions and Classes

//
// COLOR PANEL:
//
private class HSColorPanel: NSObject {
    var callbackRef: LuaValue?
    var generation: UInt64 = 0
    var observerToken: (any NotificationObserverToken)?
    weak var notificationRef: (any NotificationProtocol)?

    override init() {
        super.init()
        let cp = NSColorPanel.shared
        cp.setTarget(self)
        cp.setAction(#selector(colorCallback(_:)))
    }

    func registerObserver(_ L: UnsafeMutablePointer<lua_State>!) {
        let notif = environmentGet(L).notification
        observerToken = notif.addObserver(name: NSWindow.willCloseNotification.rawValue, object: NSColorPanel.shared) { [weak self] _ in
            self?.colorClose()
        }
        notificationRef = notif
    }

    // Second argument to callback is true indicating this is a close color panel event
    func colorClose() {
        if callbackRef != nil {
            DispatchQueue.main.async { [weak self] in
                guard let self = self, let cb = self.callbackRef else { return }
                guard lua_isStateGenerationValid(self.generation) else { return }
                let L = lua_getCurrentState()!
                let cp = NSColorPanel.shared
                cb.push(onto: L)
                NSColor_tolua(L, cp.color)
                L.push(true)
                if lua_pcall(L, 2, 0, 0) != LUA_OK { lua_pop(L, 1) }
            }
        }
    }

    // Second argument to callback is false indicating that the color panel is still open (i.e. they may change color again)
    @objc func colorCallback(_ colorPanel: NSColorPanel) {
        if callbackRef != nil {
            DispatchQueue.main.async { [weak self] in
                guard let self = self, let cb = self.callbackRef else { return }
                guard lua_isStateGenerationValid(self.generation) else { return }
                let L = lua_getCurrentState()!
                cb.push(onto: L)
                NSColor_tolua(L, colorPanel.color)
                L.push(false)
                if lua_pcall(L, 2, 0, 0) != LUA_OK { lua_pop(L, 1) }
            }
        }
    }
}

private var cpReceiverObject: HSColorPanel?

// MARK: - Color Panel Functions

/// hs.dialog.color.callback([callbackFn]) -> function or nil
/// Function
/// Sets or removes the callback function for the color panel.
///
/// Parameters:
///  * a function, or `nil` to remove the current function, which will be invoked as a callback for messages generated by this color panel. The callback function should expect 2 arguments as follows:
///    ** A table containing the color values from the color panel.
///    ** A boolean which returns `true` if the color panel has been closed otherwise `false` indicating that the color panel is still open (i.e. it may change color again).
///
/// Returns:
///  * The last callbackFn or `nil` so you can save it and re-attach it if something needs to temporarily take the callbacks.
///
/// Notes:
///  * Example:
///      `hs.dialog.color.callback(function(a,b) print("COLOR CALLBACK:\nSelected Color: " .. hs.inspect(a) .. "\nPanel Closed: " .. hs.inspect(b)) end)`
private func colorPanelCallback(_ L: LuaState) throws -> CInt {

    if let cb = cpReceiverObject!.callbackRef {
        cb.push(onto: L)
    } else {
        lua_pushnil(L)
    }
    if lua_gettop(L) == 2 { // we just added to it...
        // in either case, we need to remove an existing callback, so...
        cpReceiverObject!.callbackRef = nil
        if lua_type(L, 1) == LUA_TFUNCTION {
            cpReceiverObject!.callbackRef = L.ref(index: 1)
            cpReceiverObject!.generation = lua_currentStateGeneration()
        }
    }
    // return the *last* fn (or nil) so you can save it and re-attach it if something needs to
    // temporarily take the callbacks
    return 1
}

/// hs.dialog.color.continuous([value]) -> boolean
/// Function
/// Set or display whether or not the callback should be continuously updated when a user drags a color slider or control.
///
/// Parameters:
///  * [value] - `true` if you want to continuously trigger the callback, otherwise `false`.
///
/// Returns:
///  * `true` if continuous is enabled otherwise `false`
///
/// Notes:
///  * Example:
///      `hs.dialog.color.continuous(true)`
private func colorPanelContinuous(_ L: LuaState) throws -> CInt {
    let cp = NSColorPanel.shared
    if lua_gettop(L) == 1 {
        cp.isContinuous = lua_toboolean(L, 1) != 0
    }
    L.push(cp.isContinuous)
    return 1
}

/// hs.dialog.color.showsAlpha([value]) -> boolean
/// Function
/// Set or display whether or not the color panel should display an opacity slider.
///
/// Parameters:
///  * [value] - `true` if you want to display an opacity slider, otherwise `false`.
///
/// Returns:
///  * `true` if the opacity slider is displayed otherwise `false`
///
/// Notes:
///  * Example:
///      `hs.dialog.color.showsAlpha(true)`
private func colorPanelShowsAlpha(_ L: LuaState) throws -> CInt {
    let cp = NSColorPanel.shared
    if lua_gettop(L) == 1 {
        cp.showsAlpha = lua_toboolean(L, 1) != 0
    }
    L.push(cp.showsAlpha)
    return 1
}

/// hs.dialog.color.color([value]) -> table
/// Function
/// Set or display the currently selected color in a color wheel.
///
/// Parameters:
///  * [value] - The color values in a table (as described in `hs.drawing.color`).
///
/// Returns:
///  * A table of the currently selected color in the form of `hs.drawing.color`.
///
/// Notes:
///  * Example:
///      `hs.dialog.color.color(hs.drawing.color.blue)`
private func colorPanelColor(_ L: LuaState) throws -> CInt {
    let cp = NSColorPanel.shared
    if lua_gettop(L) == 1 {
        guard let theColor = table_toNSColor(L, 1) as? NSColor else {
            throw LuaCallError("bad argument #1 (expected color table)")
        }
        cp.color = theColor
    }
    NSColor_tolua(L, cp.color)
    return 1
}

/// hs.dialog.color.mode([value]) -> table
/// Function
/// Set or display the currently selected color panel mode.
///
/// Parameters:
///  * [value] - The mode you wish to use as a string from the following options:
///    ** "wheel" - Color Wheel
///    ** "gray" - Gray Scale Slider
///    ** "RGB" - RGB Sliders
///    ** "CMYK" - CMYK Sliders
///    ** "HSB" - HSB Sliders
///    ** "list" - Color Palettes
///    ** "custom" - Image Palettes
///    ** "crayon" - Pencils
///    ** "none"
///
/// Returns:
///  * The current mode as a string.
///
/// Notes:
///  * Example:
///      `hs.dialog.color.mode("RGB")`
private func colorPanelMode(_ L: LuaState) throws -> CInt {
    let cp = NSColorPanel.shared
    if lua_gettop(L) == 1 {
        let theMode = lua_tovalue(L, at: 1) as! String
        switch theMode {
        case "none":   cp.mode = .none
        case "gray":   cp.mode = .gray
        case "RGB":    cp.mode = .RGB
        case "CMYK":   cp.mode = .CMYK
        case "HSB":    cp.mode = .HSB
        case "custom": cp.mode = .customPalette
        case "list":   cp.mode = .colorList
        case "wheel":  cp.mode = .wheel
        case "crayon": cp.mode = .crayon
        default:
            throw LuaCallError("unknown color panel mode")
        }
    }

    switch cp.mode {
    case .none:          lua_pushany(L, "none")
    case .gray:          lua_pushany(L, "gray")
    case .RGB:           lua_pushany(L, "RGB")
    case .CMYK:          lua_pushany(L, "CMYK")
    case .HSB:           lua_pushany(L, "HSB")
    case .customPalette: lua_pushany(L, "custom")
    case .colorList:     lua_pushany(L, "list")
    case .wheel:         lua_pushany(L, "wheel")
    case .crayon:        lua_pushany(L, "crayon")
    default:
        lua_pushany(L, "** unrecognized mode:\(cp.mode.rawValue)")
    }
    return 1
}

/// hs.dialog.color.alpha([value]) -> number
/// Function
/// Set or display the selected opacity.
///
/// Parameters:
///  * [value] - A opacity value as a number between 0 and 1, where 0 is 100% transparent/see-through.
///
/// Returns:
///  * The current alpha value as a number.
///
/// Notes:
///  * Example:
///      `hs.dialog.color.alpha(0.5)`
private func colorPanelAlpha(_ L: LuaState) throws -> CInt {

    let cp = NSColorPanel.shared
    if lua_gettop(L) == 1 {
        let alpha = lua_tovalue(L, at: 1) as! NSNumber
        let color = cp.color.withAlphaComponent(CGFloat(alpha.doubleValue))
        cp.color = color
    }

    L.push(Double(NSColorPanel.shared.alpha))
    return 1
}

/// hs.dialog.color.show() -> none
/// Function
/// Shows the Color Panel.
///
/// Parameters:
///  * None
///
/// Returns:
///  * None
///
/// Notes:
///  * Example:
///      `hs.dialog.color.show()`
private func colorPanelShow(_ L: LuaState) throws -> CInt {
    NSApp.orderFrontColorPanel(nil)
    return 0
}

/// hs.dialog.color.hide() -> none
/// Function
/// Hides the Color Panel.
///
/// Parameters:
///  * None
///
/// Returns:
///  * None
///
/// Notes:
///  * Example:
///      `hs.dialog.color.hide()`
private func colorPanelHide(_ L: LuaState) throws -> CInt {
    NSColorPanel.shared.close()
    return 0
}

// MARK: - Choose File or Folder

/// hs.dialog.chooseFileOrFolder([message], [defaultPath], [canChooseFiles], [canChooseDirectories], [allowsMultipleSelection], [allowedFileTypes], [resolvesAliases]) -> string
/// Function
/// Displays a file and/or folder selection dialog box using NSOpenPanel.
///
/// Parameters:
///  * [message] - The optional message text to display.
///  * [defaultPath] - The optional path you want to dialog to open to.
///  * [canChooseFiles] - Whether or not the user can select files. Defaults to `true`.
///  * [canChooseDirectories] - Whether or not the user can select folders. Default to `false`.
///  * [allowsMultipleSelection] - Allow multiple selections of files and/or folders. Defaults to `false`.
///  * [allowedFileTypes] - An optional table of allowed file types. Defaults to `true`.
///  * [resolvesAliases] - An optional boolean that indicates whether the panel resolves aliases.
///
/// Returns:
///  * The selected files in a table or `nil` if cancel was pressed.
///
/// Notes:
///  * The optional values must be entered in order (i.e. you can't supply `allowsMultipleSelection` without also supplying `canChooseFiles` and `canChooseDirectories`).
///  * Example:
///      `hs.inspect(hs.dialog.chooseFileOrFolder("Please select a file:", "~/Desktop", true, false, true, {"jpeg", "pdf"}, true))`
private func chooseFileOrFolder(_ L: LuaState) throws -> CInt {
    // Check the Parameters:
    //              [message],                 [defaultPath],             [canChooseFiles],           [canChooseDirectories],     [allowsMultipleSelection],  [allowedFileTypes],       [resolvesAliases]

    // Allowed File Types:
    var allowedFileTypes: [String]? = nil
    if lua_istable(L, 6) {
        var types: [String] = []
        lua_pushnil(L)
        while lua_next(L, 6) != 0 {
            let item = String(cString: luaL_checkstring(L, -1))
            types.append(item)
            lua_pop(L, 1)
        }
        allowedFileTypes = types
    }

    let config = DialogConfig(
        message: lua_tovalue(L, at: 1) as? String,
        canChooseFiles: !(lua_isboolean(L, 3) && lua_toboolean(L, 3) == 0),
        canChooseDirectories: lua_isboolean(L, 4) && lua_toboolean(L, 4) != 0,
        allowsMultipleSelection: !(lua_isboolean(L, 5) && lua_toboolean(L, 5) == 0),
        allowedFileTypes: allowedFileTypes,
        initialDirectory: lua_tovalue(L, at: 2) as? String
        // Note: resolvesAliases (arg 7) is not expressible via DialogConfig; ignored.
    )

    let result = environmentGet(L).dialog.showOpenPanel(config: config)

    if let files = result.selectedFiles, !files.isEmpty {
        lua_newtable(L)
        var count: Int32 = 1
        for path in files {
            L.push(path)
            lua_setfield(L, -2, "\(count)")
            count += 1
        }
    } else {
        lua_pushnil(L)
    }

    return 1
}

// MARK: - Webview Alert

func dialog_webviewWindowFromLua(L: UnsafeMutablePointer<lua_State>!, at idx: Int32) -> HSWebViewWindow? {
    guard luaL_testudata(L, idx, wv_USERDATA_TAG) != nil else { return nil }
    return wv_getWindowFromUD(L, idx)
}

/// hs.dialog.webviewAlert(webview, callbackFn, message, [informativeText], [buttonOne], [buttonTwo], [style]) -> string
/// Function
/// Displays a simple dialog box using `NSAlert` in a `hs.webview`.
///
/// Parameters:
///  * webview - The `hs.webview` to display the alert on.
///  * callbackFn - The callback function that's called when a button is pressed.
///  * message - The message text to display.
///  * [informativeText] - Optional informative text to display.
///  * [buttonOne] - An optional value for the first button as a string. Defaults to "OK".
///  * [buttonTwo] - An optional value for the second button as a string. If `nil` is used, no second button will be displayed.
///  * [style] - An optional style of the dialog box as a string. Defaults to "warning".
///
/// Returns:
///  * nil
///
/// Notes:
///  * This alert is will prevent the user from interacting with the `hs.webview` until a button is pressed on the alert.
///  * The optional values must be entered in order (i.e. you can't supply `style` without also supplying `buttonOne` and `buttonTwo`).
///  * [style] can be "warning", "informational" or "critical". If something other than these string values is given, it will use "informational".
///  * Example:
///      ```lua
///      testCallbackFn = function(result) print("Callback Result: " .. result) end
///      testWebviewA = hs.webview.newBrowser(hs.geometry.rect(250, 250, 250, 250)):show()
///      testWebviewB = hs.webview.newBrowser(hs.geometry.rect(450, 450, 450, 450)):show()
///      hs.dialog.webviewAlert(testWebviewA, testCallbackFn, "Message", "Informative Text", "Button One", "Button Two", "warning")
///      hs.dialog.webviewAlert(testWebviewB, testCallbackFn, "Message", "Informative Text", "Single Button")```
private func webviewAlert(_ L: LuaState) throws -> CInt {
    let defaultButton = "OK"
    let defaultAlertStyle = NSAlert.Style.informational

    //                            webview,      callbackFn,   message,    [informativeText],         [buttonOne],               [buttonTwo],                         [style]

    guard let webview = dialog_webviewWindowFromLua(L: L, at: 1) else {
        throw LuaCallError("bad argument #1 (expected hs.webview object)")
    }

    var callbackRef: LuaValue? = L.ref(index: 2)

    let message = lua_tovalue(L, at: 3) as! String
    let informativeText = lua_tovalue(L, at: 4) as? String
    let buttonOne = lua_tovalue(L, at: 5) as? String
    let buttonTwo = lua_tovalue(L, at: 6) as? String
    let style = lua_tovalue(L, at: 7) as? String

    let alert = NSAlert()
    alert.messageText = message

    if let informativeText = informativeText {
        alert.informativeText = informativeText
    }

    if let buttonOne = buttonOne, !buttonOne.isEmpty {
        alert.addButton(withTitle: buttonOne)
    } else {
        alert.addButton(withTitle: defaultButton)
    }

    if let buttonTwo = buttonTwo, !buttonTwo.isEmpty {
        alert.addButton(withTitle: buttonTwo)
    }

    switch style {
    case "warning":       alert.alertStyle = .warning
    case "informational": alert.alertStyle = .informational
    case "critical":      alert.alertStyle = .critical
    default:              alert.alertStyle = defaultAlertStyle
    }

    let generation = lua_currentStateGeneration()
    alert.beginSheetModal(for: webview) { result in
        guard lua_isStateGenerationValid(generation), let L = lua_getCurrentState() else {
            callbackRef = nil
            return
        }

        var button = defaultButton

        if result == .alertFirstButtonReturn {
            if let buttonOne = buttonOne {
                button = buttonOne
            }
        } else if result == .alertSecondButtonReturn {
            button = buttonTwo ?? defaultButton
        } else {
            os_log(.error, "%{public}s", "hs.dialog.webviewAlert() - Failed to detect which button was pressed.")
            lua_pushnil(L)
        }

        callbackRef!.push(onto: L) // Put the saved function back on the stack.
        callbackRef = nil // Release the stored function from the registry.
        lua_pushany(L, button)
        if lua_pcall(L, 1, 0, 0) != LUA_OK { lua_pop(L, 1) }
    }

    lua_pushnil(L)
    return 1
}

// MARK: - Blocking Alert

/// hs.dialog.blockAlert(message, informativeText, [buttonOne], [buttonTwo], [style]) -> string
/// Function
/// Displays a simple dialog box using `NSAlert` that will halt Lua code processing until the alert is closed.
///
/// Parameters:
///  * message - The message text to display.
///  * informativeText - The informative text to display.
///  * [buttonOne] - An optional value for the first button as a string. Defaults to "OK".
///  * [buttonTwo] - An optional value for the second button as a string. If `nil` is used, no second button will be displayed.
///  * [style] - An optional style of the dialog box as a string. Defaults to "informational".
///
/// Returns:
///  * The value of the button as a string.
///
/// Notes:
///  * The optional values must be entered in order (i.e. you can't supply `style` without also supplying `buttonOne` and `buttonTwo`).
///  * [style] can be "warning", "informational" or "critical". If something other than these string values is given, it will use "warning".
///  * Example:
///      `hs.dialog.blockAlert("Message", "Informative Text", "Button One", "Button Two", "critical")`
private func blockAlert(_ L: LuaState) throws -> CInt {
    let defaultButton = "OK"

    //              message,    informativeText,
    //                                      [buttonOne],               [buttonTwo],               [style]

    let message = lua_tovalue(L, at: 1) as! String
    let informativeText = lua_tovalue(L, at: 2) as! String
    let buttonOne = lua_tovalue(L, at: 3) as? String
    let buttonTwo = lua_tovalue(L, at: 4) as? String
    let style = lua_tovalue(L, at: 5) as? String

    let alert = NSAlert()
    alert.messageText = message
    alert.informativeText = informativeText

    if let buttonOne = buttonOne, !buttonOne.isEmpty {
        alert.addButton(withTitle: buttonOne)
    } else {
        alert.addButton(withTitle: defaultButton)
    }

    if let buttonTwo = buttonTwo, !buttonTwo.isEmpty {
        alert.addButton(withTitle: buttonTwo)
    }

    switch style {
    case "warning":       alert.alertStyle = .warning
    case "informational": alert.alertStyle = .informational
    case "critical":      alert.alertStyle = .critical
    default:              alert.alertStyle = .warning
    }

    let result = alert.runModal()

    if result == .alertFirstButtonReturn {
        if buttonOne == nil {
            L.push(defaultButton)
        } else {
            lua_pushvalue(L, 3)
        }
    } else if result == .alertSecondButtonReturn {
        lua_pushvalue(L, 4)
    } else {
        os_log(.error, "%{public}s", "hs.dialog.alert() - Failed to detect which button was pressed.")
        lua_pushnil(L)
    }

    return 1
}

// MARK: - Text Prompt

/// hs.dialog.textPrompt(message, informativeText, [defaultText], [buttonOne], [buttonTwo], [secureField]) -> string, string
/// Function
/// Displays a simple text input dialog box.
///
/// Parameters:
///  * message - The message text to display
///  * informativeText - The informative text to display
///  * [defaultText] - The informative text to display
///  * [buttonOne] - An optional value for the first button as a string
///  * [buttonTwo] - An optional value for the second button as a string
///  * [secureField] - An optional boolean. If true, PasswordField instead of TextField. Defaults to false.
///
/// Returns:
///  * The value of the button as a string
///  * The value of the text input as a string
///
/// Notes:
///  * `buttonOne` defaults to "OK" if no value is supplied.
///  * `buttonOne` will also be triggered by pressing `ENTER`, whereas `buttonTwo` will be triggered by pressing `ESC`.
///  * Examples:
///      `hs.dialog.textPrompt("Main message.", "Please enter something:")`
///      `hs.dialog.textPrompt("Main message.", "Please enter something:", "Default Value", "OK")`
///      `hs.dialog.textPrompt("Main message.", "Please enter something:", "Default Value", "OK", "Cancel")`
///      `hs.dialog.textPrompt("Main message.", "Please enter something:", "", "OK", "Cancel", true)`
private func textPrompt(_ L: LuaState) throws -> CInt {
    let defaultButton = "OK"

    //              message,    informativeText,
    //                                      [defaultText],             [buttonOne],               [buttonTwo]

    let message = lua_tovalue(L, at: 1) as! String
    let informativeText = lua_tovalue(L, at: 2) as! String
    let defaultText = lua_tovalue(L, at: 3) as? String
    let buttonOne = lua_tovalue(L, at: 4) as? String
    let buttonTwo = lua_tovalue(L, at: 5) as? String
    let secureField = (lua_type(L, 6) == LUA_TBOOLEAN) ? (lua_toboolean(L, 6) != 0) : false

    let alert = NSAlert()
    alert.messageText = message
    alert.informativeText = informativeText

    if let buttonOne = buttonOne, !buttonOne.isEmpty {
        alert.addButton(withTitle: buttonOne)
    } else {
        alert.addButton(withTitle: defaultButton)
    }

    if let buttonTwo = buttonTwo, !buttonTwo.isEmpty {
        alert.addButton(withTitle: buttonTwo)
        alert.buttons[1].keyEquivalent = "\u{1b}" // Escape
        alert.buttons[0].keyEquivalent = "\r"       // Return
    } else {
        alert.buttons[0].keyEquivalent = "\r" // Return
    }

    let input: NSTextField
    if secureField {
        input = NSSecureTextField(frame: NSMakeRect(0, 0, 200, 24))
    } else {
        input = NSTextField(frame: NSMakeRect(0, 0, 200, 24))
    }

    input.stringValue = defaultText ?? ""

    alert.accessoryView = input

    // Focus on text input:
    alert.window.initialFirstResponder = input

    // Show alert:
    let result = alert.runModal()

    if result == .alertFirstButtonReturn {
        if buttonOne == nil {
            L.push(defaultButton)
            L.push(input.stringValue)
        } else {
            lua_pushvalue(L, 4)
            L.push(input.stringValue)
        }
    } else if result == .alertSecondButtonReturn {
        lua_pushvalue(L, 5)
        L.push(input.stringValue)
    } else {
        os_log(.error, "%{public}s", "hs.dialog.textPrompt() - Failed to detect which button was pressed.")
        lua_pushnil(L)
    }

    return 2
}

// MARK: - Cosmic Hammer/Lua Infrastructure

private func releaseReceivers(_ L: LuaState) throws -> CInt {
    let cp = NSColorPanel.shared
    if let token = cpReceiverObject!.observerToken {
        cpReceiverObject!.notificationRef?.removeObserver(token)
        cpReceiverObject!.observerToken = nil
    }
    cpReceiverObject!.notificationRef = nil
    cp.setTarget(nil)
    cp.setAction(nil)
    cpReceiverObject!.callbackRef = nil
    cp.close() // Close the Color Panel
    cpReceiverObject = nil

    return 0
}

@_cdecl("luaopen_hs_libdialog")
public func luaopen_hs_libdialog(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    runEntryPoint(L) { L in
        // Create module table (4 functions)
        lua_createtable(L, 0, 4)
        L.push(webviewAlert)
        lua_setfield(L, -2, "webviewAlert")
        L.push(blockAlert)
        lua_setfield(L, -2, "blockAlert")
        L.push(textPrompt)
        lua_setfield(L, -2, "textPrompt")
        L.push(chooseFileOrFolder)
        lua_setfield(L, -2, "chooseFileOrFolder")

        // Set module metatable (for __gc)
        lua_createtable(L, 0, 1)
        L.push(releaseReceivers)
        lua_setfield(L, -2, "__gc")
        lua_setmetatable(L, -2)

        // Color panel sub-table (8 functions)
        lua_createtable(L, 0, 8)
        L.push(colorPanelAlpha)
        lua_setfield(L, -2, "alpha")
        L.push(colorPanelCallback)
        lua_setfield(L, -2, "callback")
        L.push(colorPanelColor)
        lua_setfield(L, -2, "color")
        L.push(colorPanelContinuous)
        lua_setfield(L, -2, "continuous")
        L.push(colorPanelMode)
        lua_setfield(L, -2, "mode")
        L.push(colorPanelShowsAlpha)
        lua_setfield(L, -2, "showsAlpha")
        L.push(colorPanelShow)
        lua_setfield(L, -2, "show")
        L.push(colorPanelHide)
        lua_setfield(L, -2, "hide")
        lua_setfield(L, -2, "color")
        NSColorPanel.setPickerMask(NSColorPanel.Options(rawValue: 0xFFFF))
        cpReceiverObject = HSColorPanel()
        cpReceiverObject!.registerObserver(L)
    }
}
