//
//  LuaRuntime.swift
//  Cosmic Hammer
//
//  Ported from MJLua.m by Mohammad Sadegh Khoeini.
//  Copyright © 2026 Cosmic Hammer. All rights reserved.
//

import Cocoa
import CLua
import Lua
import HSDSTCore
import AVFoundation
import os.log

// MARK: - Module-level state (formerly static C variables)

private var MJLuaLogDelegate: AnyObject?
private var evalfn: Int32 = LUA_NOREF
private var completionsForWordFn: Int32 = LUA_NOREF
private var oldPanicFunction: lua_CFunction?
private var loghandler: (@convention(block) (NSString) -> Void)?

// MARK: - String constants (from variables.h)

private let HSAutoLoadExtensions = "HSAutoLoadExtensions"

// MARK: - Extension registration (generated by scripts/generate-hsextensions.sh)
// hsExtensionsRegisterAll() is defined in HSExtensionsGenerated.swift (same module).

// MARK: - Lua boot contract

enum LuaBoot {
    struct Context: Equatable {
        let extensionsPath: String
        let configFileDisplayPath: String
        let configFilePath: String
        let configDir: String
        let dataDir: String
        let docsJSONPath: String
        let hasInitFile: Bool
        let autoloadExtensions: Bool
    }

    struct LifecycleReferences: Equatable {
        let evalFunctionRef: Int32
        let completionsFunctionRef: Int32
    }

    enum Error: Swift.Error, CustomStringConvertible {
        case loadFailed(String)
        case runtimeFailed(String)
        case invalidLifecycle(String)

        var description: String {
            switch self {
            case .loadFailed(let message),
                 .runtimeFailed(let message),
                 .invalidLifecycle(let message):
                return message
            }
        }
    }

    static func runSetup(
        _ L: UnsafeMutablePointer<lua_State>,
        setupPath: String,
        context: Context
    ) throws -> LifecycleReferences {
        precondition(!setupPath.isEmpty, "setup path must not be empty")
        precondition(!context.extensionsPath.isEmpty, "extensions path must not be empty")
        let baseTop = lua_gettop(L)
        let loadResult = luaL_loadfilex(L, (setupPath as NSString).fileSystemRepresentation, nil)
        guard loadResult == LUA_OK else {
            let message = readString(L, at: -1) ?? "(unknown error)"
            lua_settop(L, baseTop)
            throw Error.loadFailed("Unable to load setup.lua: \(message)")
        }

        pushContext(L, context)

        guard lua_pcall(L, 1, 1, 0) == LUA_OK else {
            let message = readString(L, at: -1) ?? "(unknown error)"
            lua_settop(L, baseTop)
            throw Error.runtimeFailed("Error running setup.lua: \(message)")
        }

        guard lua_type(L, -1) == LUA_TTABLE else {
            let actual = typeName(L, at: -1)
            lua_settop(L, baseTop)
            throw Error.invalidLifecycle("setup.lua returned \(actual); expected one lifecycle table")
        }

        let lifecycleIndex = lua_absindex(L, -1)
        lua_getfield(L, lifecycleIndex, "runString")
        lua_getfield(L, lifecycleIndex, "completionsForInputString")

        let runStringType = lua_type(L, -2)
        let completionsType = lua_type(L, -1)
        guard runStringType == LUA_TFUNCTION, completionsType == LUA_TFUNCTION else {
            let message = "setup.lua lifecycle table must contain function fields runString and completionsForInputString; got \(typeName(runStringType)) and \(typeName(completionsType))"
            lua_settop(L, baseTop)
            throw Error.invalidLifecycle(message)
        }

        let completionsRef = luaL_ref(L, LUA_REGISTRYINDEX_VALUE)
        let evalRef = luaL_ref(L, LUA_REGISTRYINDEX_VALUE)
        lua_pop(L, 1)

        assert(evalRef != LUA_NOREF, "evalFunctionRef must be a valid registry reference")
        assert(evalRef != LUA_REFNIL, "evalFunctionRef must not be nil ref")
        assert(completionsRef != LUA_NOREF, "completionsFunctionRef must be a valid registry reference")
        assert(completionsRef != LUA_REFNIL, "completionsFunctionRef must not be nil ref")
        assert(lua_gettop(L) == baseTop, "stack must be balanced after runSetup")

        return LifecycleReferences(
            evalFunctionRef: evalRef,
            completionsFunctionRef: completionsRef
        )
    }

    static func pushContext(_ L: UnsafeMutablePointer<lua_State>, _ context: Context) {
        let baseTop = lua_gettop(L)
        lua_createtable(L, 0, 8)
        setField(L, "extensionsPath", context.extensionsPath)
        setField(L, "configFileDisplayPath", context.configFileDisplayPath)
        setField(L, "configFilePath", context.configFilePath)
        setField(L, "configDir", context.configDir)
        setField(L, "dataDir", context.dataDir)
        setField(L, "docsJSONPath", context.docsJSONPath)
        setField(L, "hasInitFile", context.hasInitFile)
        setField(L, "autoloadExtensions", context.autoloadExtensions)
        assert(lua_gettop(L) == baseTop + 1, "pushContext must leave exactly one table on the stack")
        assert(lua_type(L, -1) == LUA_TTABLE, "pushContext must leave a table on top of the stack")
    }

    private static func setField(_ L: UnsafeMutablePointer<lua_State>, _ name: String, _ value: String) {
        _ = value.withCString { lua_pushstring(L, $0) }
        name.withCString { lua_setfield(L, -2, $0) }
    }

    private static func setField(_ L: UnsafeMutablePointer<lua_State>, _ name: String, _ value: Bool) {
        lua_pushboolean(L, value ? 1 : 0)
        name.withCString { lua_setfield(L, -2, $0) }
    }

    private static func readString(_ L: UnsafeMutablePointer<lua_State>, at index: Int32) -> String? {
        var len: Int = 0
        guard let raw = lua_tolstring(L, index, &len) else { return nil }
        return String(data: Data(bytes: raw, count: len), encoding: .utf8)
            ?? String(cString: raw)
    }

    private static func typeName(_ L: UnsafeMutablePointer<lua_State>, at index: Int32) -> String {
        typeName(lua_type(L, index))
    }

    private static func typeName(_ type: Int32) -> String {
        guard let name = lua_typename(nil, type) else { return "unknown" }
        return String(cString: name)
    }
}

// MARK: - Log handler setup

@_cdecl("MJLuaSetupLogHandler")
func MJLuaSetupLogHandler(_ blk: @escaping @convention(block) (NSString) -> Void) {
    loghandler = blk
}

// MARK: - Core Lua functions

/// hs.autoLaunch([state]) -> bool
/// Function
/// Set or display the "Launch on Login" status for Cosmic Hammer.
///
/// Parameters:
///  * state - an optional boolean which will set whether or not Cosmic Hammer should be launched automatically when you log into your computer.
///
/// Returns:
///  * True if Cosmic Hammer is currently (or has just been) set to launch on login or False if Cosmic Hammer is not.
private func core_autolaunch(_ L: LuaState) throws -> CInt {
    if lua_isboolean(L, 1) { MJAutoLaunchSet(lua_toboolean(L, 1) != 0) }
    lua_pushboolean(L, MJAutoLaunchGet() ? 1 : 0)
    return 1
}

/// hs.menuIcon([state]) -> bool
/// Function
/// Set or display whether or not the Cosmic Hammer menu icon is visible.
///
/// Parameters:
///  * state - an optional boolean which will set whether or not the Cosmic Hammer menu icon should be visible.
///
/// Returns:
///  * True if the icon is currently set (or has just been) to be visible or False if it is not.
private func core_menuicon(_ L: LuaState) throws -> CInt {
    if lua_isboolean(L, 1) { MJMenuIconSetVisible(lua_toboolean(L, 1) != 0) }
    lua_pushboolean(L, MJMenuIconVisible() ? 1 : 0)
    return 1
}

/// hs.consoleOnTop([state]) -> bool
/// Function
/// Set or display whether or not the Cosmic Hammer console is always on top when visible.
///
/// Parameters:
///  * state - an optional boolean which will set whether or not the Cosmic Hammer console is always on top when visible.
///
/// Returns:
///  * True if the console is currently set (or has just been) to be always on top when visible or False if it is not.
private func core_consoleontop(_ L: LuaState) throws -> CInt {
    if lua_isboolean(L, 1) { MJConsoleWindowSetAlwaysOnTop(lua_toboolean(L, 1) != 0) }
    lua_pushboolean(L, MJConsoleWindowAlwaysOnTop() ? 1 : 0)
    return 1
}

/// hs.openAbout()
/// Function
/// Displays the OS X About panel for Cosmic Hammer; implicitly focuses Cosmic Hammer.
///
/// Parameters:
///  * None
///
/// Returns:
///  * None
private func core_openabout(_ L: LuaState) throws -> CInt {
    NSApplication.shared.activate()
    NSApplication.shared.orderFrontStandardAboutPanel(nil)
    return 0
}

/// hs.openPreferences()
/// Function
/// Displays the Cosmic Hammer Preferences panel; implicitly focuses Cosmic Hammer.
///
/// Parameters:
///  * None
///
/// Returns:
///  * None
private func core_openpreferences(_ L: LuaState) throws -> CInt {
    NSApplication.shared.activate()
    MJPreferencesWindowController.singleton().showWindow(nil)
    return 0
}

/// hs.closePreferences()
/// Function
/// Closes the Cosmic Hammer Preferences window
///
/// Parameters:
///  * None
///
/// Returns:
///  * None
private func core_closepreferences(_ L: LuaState) throws -> CInt {
    MJPreferencesWindowController.singleton().window?.orderOut(nil)
    return 0
}

/// hs.openConsole([bringToFront])
/// Function
/// Opens the Cosmic Hammer Console window and optionally focuses it.
///
/// Parameters:
///  * bringToFront - if true (default), the console will be focused as well as opened.
///
/// Returns:
///  * None
private func core_openconsole(_ L: LuaState) throws -> CInt {
    if !(lua_isboolean(L, 1) && lua_toboolean(L, 1) == 0) {
        NSApplication.shared.activate()
    }
    MJConsoleWindowController.singleton().showWindow(nil)
    return 0
}

/// hs.closeConsole()
/// Function
/// Closes the Cosmic Hammer Console window
///
/// Parameters:
///  * None
///
/// Returns:
///  * None
private func core_closeconsole(_ L: LuaState) throws -> CInt {
    MJConsoleWindowController.singleton().window?.orderOut(nil)
    return 0
}

/// hs.open(filePath)
/// Function
/// Opens a file as if it were opened with /usr/bin/open
///
/// Parameters:
///  * filePath - A string containing the path to a file/bundle to open
///
/// Returns:
///  * A boolean, true if the file was opened successfully, otherwise false
private func core_open(_ L: LuaState) throws -> CInt {
    luaL_checktype(L, 1, LUA_TSTRING)

    guard let cStr = lua_tostring(L, 1) else {
        lua_pushboolean(L, 0)
        return 1
    }
    let path = String(cString: cStr)
    let result = environmentGet(L).workspace.openFile(path)

    lua_pushboolean(L, result ? 1 : 0)
    return 1
}

/// hs.reload()
/// Function
/// Reloads your init-file in a fresh Lua environment.
///
/// Parameters:
///  * None
///
/// Returns:
///  * None
private func core_reload(_ L: LuaState) throws -> CInt {
    DispatchQueue.main.async {
        MJLuaReplace()
    }
    return 0
}

/// hs.processInfo
/// Constant
/// A table containing read-only information about the Cosmic Hammer application instance currently running.
private func push_hammerAppInfo(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    precondition(L != nil, "Lua state must not be nil")
    let baseTop = lua_gettop(L)
    // Fetch the CPU architecture in use
    var arch = "Unknown"
    var utsname = utsname()
    if uname(&utsname) == 0 {
        arch = withUnsafePointer(to: &utsname.machine) {
            $0.withMemoryRebound(to: CChar.self, capacity: Int(_SYS_NAMELEN)) {
                String(cString: $0)
            }
        }
    }

    let bundle = Bundle.main
    let infoDictionary = bundle.infoDictionary ?? [:]

    #if DEBUG
    let isDebugBuild = true
    #else
    let isDebugBuild = false
    #endif

    let appInfo: [String: Any] = [
        "version": infoDictionary["CFBundleShortVersionString"] as? String ?? "",
        "build": infoDictionary["CFBundleVersion"] as? String ?? "",
        "resourcePath": String(cString: (bundle.resourcePath! as NSString).fileSystemRepresentation),
        "bundlePath": String(cString: (bundle.bundlePath as NSString).fileSystemRepresentation),
        "executablePath": String(cString: (bundle.executablePath! as NSString).fileSystemRepresentation),
        "frameworksPath": String(cString: (bundle.privateFrameworksPath! as NSString).fileSystemRepresentation),
        "processID": getpid(),
        "bundleID": bundle.bundleIdentifier ?? "",
        "arch": arch,
        "isRosetta": false,
        "buildTime": {
            if let execPath = Bundle.main.executablePath,
               let attrs = try? environmentGet(L).fileSystem.attributesOfItem(atPath: execPath),
               let modDate = attrs.modificationDate {
                let fmt = DateFormatter()
                fmt.dateFormat = "MMM dd yyyy, HH:mm:ss"
                return fmt.string(from: modDate)
            }
            return "Unknown"
        }(),
        "debugBuild": isDebugBuild,
    ]

    lua_pushany(L, appInfo as NSDictionary)
    assert(lua_gettop(L) == baseTop + 1, "push_hammerAppInfo must push exactly one value")
    return 1
}

/// hs.accessibilityState(shouldPrompt) -> isEnabled
/// Function
/// Checks the Accessibility Permissions for Cosmic Hammer, and optionally allows you to prompt for permissions.
///
/// Parameters:
///  * shouldPrompt - an optional boolean value indicating if the dialog box asking if the System Preferences application should be opened should be presented when Accessibility is not currently enabled for Cosmic Hammer.  Defaults to false.
///
/// Returns:
///  * True or False indicating whether or not Accessibility is enabled for Cosmic Hammer.
///
/// Notes:
///  * Since this check is done automatically when Cosmic Hammer loads, it is probably of limited use except for skipping things that are known to fail when Accessibility is not enabled.  Evettaps which try to capture keyUp and keyDown events, for example, will fail until Accessibility is enabled and the Cosmic Hammer application is relaunched.
private func core_accessibilityState(_ L: LuaState) throws -> CInt {
    let shouldprompt = lua_toboolean(L, 1) != 0
    let enabled = MJAccessibilityIsEnabled()
    if shouldprompt { MJAccessibilityOpenPanel() }
    lua_pushboolean(L, enabled ? 1 : 0)
    return 1
}

// SOURCE: https://stackoverflow.com/a/58985069
private func isScreenRecordingEnabled() -> Bool {
    var canRecordScreen = false
    let runningApplication = NSRunningApplication.current
    let ourProcessIdentifier = runningApplication.processIdentifier
    assert(ourProcessIdentifier > 0, "process identifier must be positive")

    guard let windowList = CGWindowListCopyWindowInfo(.optionOnScreenOnly, kCGNullWindowID) as? [[String: Any]] else {
        return false
    }

    for windowInfo in windowList {
        guard let processIdentifier = windowInfo[kCGWindowOwnerPID as String] as? pid_t else {
            continue
        }

        // don't check windows owned by this process
        if processIdentifier != ourProcessIdentifier {
            guard let windowRunningApplication = NSRunningApplication(processIdentifier: processIdentifier) else {
                // ignore processes we don't have access to, such as WindowServer
                continue
            }

            let windowName = windowInfo[kCGWindowName as String] as? String
            if let windowName = windowName {
                let windowExecutableName = windowRunningApplication.executableURL?.lastPathComponent
                if windowExecutableName == "Dock" {
                    // ignore the Dock, which provides the desktop picture
                    continue
                }
                canRecordScreen = true
                break
            }
        }
    }

    return canRecordScreen
}

/// hs.screenRecordingState(shouldPrompt) -> isEnabled
/// Function
/// Checks the Screen Recording Permissions for Cosmic Hammer, and optionally allows you to prompt for permissions.
///
/// Parameters:
///  * shouldPrompt - an optional boolean value indicating if the dialog box asking if the System Preferences application should be opened should be presented when Screen Recording is not currently enabled for Cosmic Hammer.  Defaults to false.
///
/// Returns:
///  * True or False indicating whether or not Screen Recording is enabled for Cosmic Hammer.
///
/// Notes:
///  * If you trigger the prompt and the user denies it, you cannot bring up the prompt again - the user must manually enable it in System Preferences.
private func core_screenRecordingState(_ L: LuaState) throws -> CInt {
    let shouldprompt = lua_toboolean(L, 1) != 0
    let enabled = isScreenRecordingEnabled()
    if shouldprompt {
        // CGDisplayStreamCreate is obsoleted in macOS 15 SDK but still works at runtime.
        // We use it only to trigger the screen recording permission prompt.
        typealias CGDisplayStreamCreateFunc = @convention(c) (
            CGDirectDisplayID, Int, Int, Int32, CFDictionary?,
            @convention(block) (Int32, UInt64, IOSurfaceRef?, CGDisplayStreamUpdate?) -> Void
        ) -> CGDisplayStream?

        if let sym = dlsym(dlopen(nil, RTLD_LAZY), "CGDisplayStreamCreate") {
            let createStream = unsafeBitCast(sym, to: CGDisplayStreamCreateFunc.self)
            let stream = createStream(
                CGMainDisplayID(), 1, 1,
                Int32(kCVPixelFormatType_32BGRA), nil,
                { _, _, _, _ in }
            )
            // stream is autoreleased / ARC-managed
            _ = stream
        }
    }
    lua_pushboolean(L, enabled ? 1 : 0)
    return 1
}

/// hs.microphoneState(shouldPrompt) -> boolean
/// Function
/// Checks the Microphone Permissions for Cosmic Hammer, and optionally allows you to prompt for permissions.
///
/// Parameters:
///  * shouldPrompt - an optional boolean value indicating if we should request microphone access. Defaults to false.
///
/// Returns:
///  * `true` or `false` indicating whether or not Microphone access is enabled for Cosmic Hammer.
///
/// Notes:
///  * Will always return `true` on macOS 10.13 or earlier.
private func core_microphoneState(_ L: LuaState) throws -> CInt {
    let shouldprompt = lua_toboolean(L, 1) != 0

    switch AVCaptureDevice.authorizationStatus(for: .audio) {
    case .authorized:
        lua_pushboolean(L, 1)
    case .notDetermined:
        if shouldprompt {
            AVCaptureDevice.requestAccess(for: .audio) { granted in
                if !granted {
                    os_log(.default, "Cosmic Hammer has been declined Microphone access by the user.")
                }
            }
        }
        lua_pushboolean(L, 0)
    case .denied, .restricted:
        lua_pushboolean(L, 0)
    @unknown default:
        lua_pushboolean(L, 0)
    }
    return 1
}

/// hs.cameraState(shouldPrompt) -> boolean
/// Function
/// Checks the Camera Permissions for Cosmic Hammer, and optionally allows you to prompt for permissions.
///
/// Parameters:
///  * shouldPrompt - an optional boolean value indicating if we should request camera access. Defaults to false.
///
/// Returns:
///  * `true` or `false` indicating whether or not Camera access is enabled for Cosmic Hammer.
///
/// Notes:
///  * Will always return `true` on macOS 10.13 or earlier.
private func core_cameraState(_ L: LuaState) throws -> CInt {
    let shouldprompt = lua_toboolean(L, 1) != 0

    switch AVCaptureDevice.authorizationStatus(for: .video) {
    case .authorized:
        lua_pushboolean(L, 1)
    case .notDetermined:
        if shouldprompt {
            AVCaptureDevice.requestAccess(for: .video) { granted in
                if !granted {
                    os_log(.default, "Cosmic Hammer has been declined Camera access by the user.")
                }
            }
        }
        lua_pushboolean(L, 0)
    case .denied, .restricted:
        lua_pushboolean(L, 0)
    @unknown default:
        lua_pushboolean(L, 0)
    }
    return 1
}

/// hs.preferencesDarkMode([state]) -> bool
/// Function
/// Set or display whether or not the Preferences panel should display in dark mode.
///
/// Parameters:
///  * state - an optional boolean which will set whether or not the Preferences panel should display in dark mode.
///
/// Returns:
///  * A boolean, true if dark mode is enabled otherwise false.
private func preferencesDarkMode(_ L: LuaState) throws -> CInt {
    if lua_isboolean(L, 1) {
        PreferencesDarkModeSetEnabled(lua_toboolean(L, 1) != 0)
        MJPreferencesWindowController.singleton().reflectDefaults()
    }

    lua_pushboolean(L, PreferencesDarkModeEnabled() ? 1 : 0)
    return 1
}

/// hs.allowAppleScript([state]) -> bool
/// Function
/// Set or display whether or not external Cosmic Hammer AppleScript commands are allowed.
///
/// Parameters:
///  * state - an optional boolean which will set whether or not external Cosmic Hammer's AppleScript commands are allowed.
///
/// Returns:
///  * A boolean, `true` if Cosmic Hammer's AppleScript commands are (or has just been) allowed, otherwise `false`.
///
/// Notes:
///  * AppleScript access is disallowed by default.
///  * However due to the way AppleScript support works, Cosmic Hammer will always allow AppleScript commands that are part of the "Standard Suite", such as `name`, `quit`, `version`, etc. However, Cosmic Hammer will only allow commands from the "Cosmic Hammer Suite" if `hs.allowAppleScript()` is set to `true`.
///  * For a full list of AppleScript Commands:
///      - Open `/Applications/Utilities/Script Editor.app`
///      - Click `File > Open Dictionary...`
///      - Select Cosmic Hammer from the list of Applications
///      - This will now open a Dictionary containing all of the available Cosmic Hammer AppleScript commands.
///  * Note that strings within the Lua code you pass from AppleScript can be delimited by `[[` and `]]` rather than normal quotes
///  * Example:
///    ```lua
///    tell application "Cosmic Hammer"
///      execute lua code "hs.alert([[Hello from AppleScript]])"
///    end tell```
private func core_appleScript(_ L: LuaState) throws -> CInt {
    if lua_isboolean(L, 1) {
        HSAppleScriptSetEnabled(lua_toboolean(L, 1) != 0)
    }

    lua_pushboolean(L, HSAppleScriptEnabled() ? 1 : 0)
    return 1
}

/// hs.openConsoleOnDockClick([state]) -> bool
/// Function
/// Set or display whether or not the Console window will open when the Cosmic Hammer dock icon is clicked
///
/// Parameters:
///  * state - An optional boolean, true if the console window should open, false if not
///
/// Returns:
///  * A boolean, true if the console window will open when the dock icon
///
/// Notes:
///  * This only refers to dock icon clicks while Cosmic Hammer is already running. The console window is not opened by launching the app
private func core_openConsoleOnDockClick(_ L: LuaState) throws -> CInt {
    if lua_isboolean(L, 1) {
        HSOpenConsoleOnDockClickSetEnabled(lua_toboolean(L, 1) != 0)
    }

    lua_pushboolean(L, HSOpenConsoleOnDockClickEnabled() ? 1 : 0)
    return 1
}

/// hs.focus()
/// Function
/// Makes Cosmic Hammer the foreground app.
///
/// Parameters:
///  * None
///
/// Returns:
///  * None
private func core_focus(_ L: LuaState) throws -> CInt {
    NSApplication.shared.activate()
    return 0
}

/// hs.getObjectMetatable(name) -> table or nil
/// Function
/// Fetches the Lua metatable for objects produced by an extension
///
/// Parameters:
///  * name - A string containing the name of a module to fetch object metadata for (e.g. `"hs.screen"`)
///
/// Returns:
///  * The extension's object metatable, or nil if an error occurred
private func core_getObjectMetatable(_ L: LuaState) throws -> CInt {
    luaL_checktype(L, 1, LUA_TSTRING)
    let name = lua_tostring(L, 1)
    luaL_getmetatable(L, name)
    if lua_istable(L, -1) != 0 {
        lua_getfield(L, -1, "__type")
        if lua_isnil(L, -1) != 0, let name = name {
            lua_pop(L, 1)
            lua_pushstring(L, name)
            lua_setfield(L, -2, "__type")
        } else {
            lua_pop(L, 1)
        }
    }
    return 1
}

/// hs.cleanUTF8forConsole(inString) -> outString
/// Function
/// Returns a copy of the incoming string that can be displayed in the Cosmic Hammer console.  Invalid UTF8 sequences are converted to the Unicode Replacement Character and NULL (0x00) is converted to the Unicode Empty Set character.
///
/// Parameters:
///  * inString - the string to be cleaned up
///
/// Returns:
///  * outString - the cleaned up version of the input string.
///
/// Notes:
///  * This function is applied automatically to all output which appears in the Cosmic Hammer console, but not to the output provided by the `hs` command line tool.
///  * This function does not modify the original string - to actually replace it, assign the result of this function to the original string.
///  * This function is a more specifically targeted version of the `hs.utf8.fixUTF8(...)` function.
private func core_cleanUTF8(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    precondition(L != nil, "Lua state must not be nil")
    luaL_checkany(L, 1)
    // luaL_tolstring coerces any value to a string representation
    var len: Int = 0
    let src = luaL_tolstring(L, 1, &len)
    let cleaned = getValidUTF8(src, ofLength: len)
    lua_pop(L, 1) // pop the luaL_tolstring result
    lua_pushany(L, cleaned)
    return 1
}

private func core_exit(_ L: LuaState) throws -> CInt {
    NSApplication.shared.terminate(nil)
    return 0
}

private func core_logmessage(_ L: LuaState) throws -> CInt {
    var len: Int = 0
    let s = lua_tolstring(L, 1, &len)
    var str: String?
    if let s = s {
        str = String(data: Data(bytes: s, count: len), encoding: .utf8)
    }
    if str == nil {
        _ = core_cleanUTF8(L)
        let s2 = lua_tolstring(L, -1, &len)
        if let s2 = s2 {
            str = String(data: Data(bytes: s2, count: len), encoding: .utf8)
        }
        lua_pop(L, 1)
    }
    loghandler?(NSString(string: str ?? ""))
    return 0
}

private func core_notify(_ L: LuaState) throws -> CInt {
    var len: Int = 0
    let s = lua_tolstring(L, 1, &len)
    var str = ""
    if let s = s {
        str = String(data: Data(bytes: s, count: len), encoding: .utf8) ?? ""
    }
    MJUserNotificationManager.sharedManager.sendNotification(str) {
        MJConsoleWindowController.singleton().showWindow(nil)
    }
    return 0
}

// MARK: - Core library registration

// MARK: - UTF-8 validation helper

/// Sanitize a byte buffer into valid UTF-8, replacing NULL bytes with the
/// Unicode Empty Set character (U+2205) and invalid sequences with the
/// Unicode Replacement Character (U+FFFD).
private func getValidUTF8(_ src: UnsafePointer<CChar>?, ofLength sourceLength: Int) -> String {
    precondition(sourceLength >= 0, "source length must not be negative")
    guard let src = src, sourceLength > 0 else { return "" }
    let nullChar: [UInt8] = [0xE2, 0x88, 0x85]     // U+2205
    let invalidChar: [UInt8] = [0xEF, 0xBF, 0xBD]  // U+FFFD

    // Rebind CChar pointer to UInt8 for unsigned byte comparisons
    let bytes = UnsafeBufferPointer(start: UnsafeRawPointer(src).assumingMemoryBound(to: UInt8.self),
                                    count: sourceLength)

    var dest = Data()
    dest.reserveCapacity(sourceLength)
    var pos = 0
    while pos < sourceLength {
        let b = bytes[pos]
        if b > 0 && b <= 127 {
            dest.append(b); pos += 1
        } else if b >= 194 && b <= 223 && pos + 1 < sourceLength &&
                    bytes[pos + 1] >= 128 && bytes[pos + 1] <= 191 {
            dest.append(b); dest.append(bytes[pos + 1]); pos += 2
        } else if b >= 224 && b <= 239 && pos + 2 < sourceLength &&
                    bytes[pos + 1] >= 128 && bytes[pos + 1] <= 191 &&
                    bytes[pos + 2] >= 128 && bytes[pos + 2] <= 191 {
            dest.append(b); dest.append(bytes[pos + 1]); dest.append(bytes[pos + 2]); pos += 3
        } else if b >= 240 && b <= 244 && pos + 3 < sourceLength &&
                    bytes[pos + 1] >= 128 && bytes[pos + 1] <= 191 &&
                    bytes[pos + 2] >= 128 && bytes[pos + 2] <= 191 &&
                    bytes[pos + 3] >= 128 && bytes[pos + 3] <= 191 {
            dest.append(b); dest.append(bytes[pos + 1]); dest.append(bytes[pos + 2]); dest.append(bytes[pos + 3]); pos += 4
        } else {
            if b == 0 {
                dest.append(contentsOf: nullChar)
            } else {
                dest.append(contentsOf: invalidChar)
            }
            pos += 1
        }
    }
    return String(data: dest, encoding: .utf8) ?? ""
}

// MARK: - Lua environment lifecycle, high level

/// Create and configure a Lua environment
@_cdecl("MJLuaCreate")
func MJLuaCreate() {
    MJLuaAlloc()
    MJLuaInit()
    os_log(.info, "Created Lua instance")
}

/// Deconfigure and destroy a Lua environment
@_cdecl("MJLuaDestroy")
func MJLuaDestroy() {
    os_log(.info, "Destroying Lua instance")
    MJLuaDeinit()
    MJLuaDealloc()
}

/// Deconfigure and destroy a Lua environment and create its replacement
@_cdecl("MJLuaReplace")
func MJLuaReplace() {
    MJLuaDeinit()
    MJLuaDealloc()
    MJConsoleWindowController.singleton().initializeConsoleColorsAndFont()

    MJLuaAlloc()
    MJLuaInit()
}

// MARK: - Lua environment lifecycle, low level

private func MJLuaAtPanic(_ L: UnsafeMutablePointer<lua_State>?) -> Int32 {
    os_log(.fault, "LUA_AT_PANIC: %{public}s", lua_tostring(L, -1).map { String(cString: $0) } ?? "<nil>")
    if let oldPanicFunction = oldPanicFunction {
        return oldPanicFunction(L)
    }
    return 0
}

/// Create a Lua environment
@_cdecl("MJLuaAlloc")
func MJLuaAlloc() {
    let traceState = CHTrace.signposter.beginInterval("LuaAlloc")
    defer { CHTrace.signposter.endInterval("LuaAlloc", traceState) }

    if MJLuaLogDelegate == nil {
        MJLuaLogDelegate = HSLoggerCreateWithLua(nil)
    }
    var L = lua_getCurrentState()
    if L == nil {
        L = luaL_newstate()
        luaL_openlibs(L)
        let env = createProductionEnvironment()
        environmentAttach(L, env)
        environmentSetGlobal(env)
        lua_setCurrentState(L)
        lua_bumpStateGeneration()
    }
    HSLoggerSetLuaState(MJLuaLogDelegate!, L)
    oldPanicFunction = lua_atpanic(L, MJLuaAtPanic)
}

/// Configure a Lua environment that has already been created
@_cdecl("MJLuaInit")
func MJLuaInit() {
    let traceState = CHTrace.signposter.beginInterval("LuaInit")
    defer { CHTrace.signposter.endInterval("LuaInit", traceState) }

    let L = lua_getCurrentState()!

    registerHSGlobalTable(L)
    installLuaSkinCompatibilityGlobals(L)

    // Register every bundled hs.lib<name> entry point into package.preload before setup.lua runs.
    let extRegState = CHTrace.signposter.beginInterval("RegisterExtensions")
    hsExtensionsRegisterAll(L)
    CHTrace.signposter.endInterval("RegisterExtensions", extRegState)

    guard let setupPath = Bundle.main.path(forResource: "setup", ofType: "lua"),
          let extensionsPath = Bundle.main.path(forResource: "extensions", ofType: nil),
          let docsPath = Bundle.main.path(forResource: "docs", ofType: "json") else {
        terminateWithCorruptInstallationAlert()
        return
    }

    let context = buildBootContext(L, extensionsPath: extensionsPath, docsPath: docsPath)
    let setupState = CHTrace.signposter.beginInterval("RunSetupLua")
    runSetupOrTerminate(L, setupPath: setupPath, context: context)
    CHTrace.signposter.endInterval("RunSetupLua", setupState)
}

/// Register the core library as the "hs" global table with all built-in functions.
private func registerHSGlobalTable(_ L: UnsafeMutablePointer<lua_State>) {
    lua_createtable(L, 0, 23)
    L.push(preferencesDarkMode)
    lua_setfield(L, -2, "preferencesDarkMode")
    L.push(core_openConsoleOnDockClick)
    lua_setfield(L, -2, "openConsoleOnDockClick")
    L.push(core_openconsole)
    lua_setfield(L, -2, "openConsole")
    L.push(core_closeconsole)
    lua_setfield(L, -2, "closeConsole")
    L.push(core_consoleontop)
    lua_setfield(L, -2, "consoleOnTop")
    L.push(core_openabout)
    lua_setfield(L, -2, "openAbout")
    L.push(core_menuicon)
    lua_setfield(L, -2, "menuIcon")
    L.push(core_openpreferences)
    lua_setfield(L, -2, "openPreferences")
    L.push(core_closepreferences)
    lua_setfield(L, -2, "closePreferences")
    L.push(core_open)
    lua_setfield(L, -2, "open")
    L.push(core_autolaunch)
    lua_setfield(L, -2, "autoLaunch")
    L.push(core_appleScript)
    lua_setfield(L, -2, "allowAppleScript")
    L.push(core_reload)
    lua_setfield(L, -2, "reload")
    L.push(core_focus)
    lua_setfield(L, -2, "focus")
    L.push(core_accessibilityState)
    lua_setfield(L, -2, "accessibilityState")
    L.push(core_screenRecordingState)
    lua_setfield(L, -2, "screenRecordingState")
    L.push(core_microphoneState)
    lua_setfield(L, -2, "microphoneState")
    L.push(core_cameraState)
    lua_setfield(L, -2, "cameraState")
    L.push(core_getObjectMetatable)
    lua_setfield(L, -2, "getObjectMetatable")
    L.push(core_cleanUTF8)
    lua_setfield(L, -2, "cleanUTF8forConsole")
    L.push(core_exit)
    lua_setfield(L, -2, "_exit")
    L.push(core_logmessage)
    lua_setfield(L, -2, "_logmessage")
    L.push(core_notify)
    lua_setfield(L, -2, "_notify")
    push_hammerAppInfo(L)
    lua_setfield(L, -2, "processInfo")
    lua_setglobal(L, "hs")
}

private func terminateWithCorruptInstallationAlert() {
    os_log(.fault, "Unable to find boot resources in bundle. Terminating")
    let alert = NSAlert()
    alert.addButton(withTitle: "OK")
    alert.messageText = "Cosmic Hammer installation is corrupted"
    alert.informativeText = "Please re-install Cosmic Hammer"
    alert.alertStyle = .critical
    alert.runModal()
    NSApplication.shared.terminate(nil)
}

private func buildBootContext(_ L: UnsafeMutablePointer<lua_State>, extensionsPath: String, docsPath: String) -> LuaBoot.Context {
    LuaBoot.Context(
        extensionsPath: extensionsPath,
        configFileDisplayPath: MJConfigFileGet() as String,
        configFilePath: MJConfigFileFullPath() as String,
        configDir: MJConfigDir() as String,
        dataDir: XDGPaths.dataHome,
        docsJSONPath: docsPath,
        hasInitFile: environmentGet(L).fileSystem.fileExists(atPath: MJConfigFileFullPath() as String),
        autoloadExtensions: environmentGet(L).settings.bool(forKey: HSAutoLoadExtensions)
    )
}

private func runSetupOrTerminate(_ L: UnsafeMutablePointer<lua_State>, setupPath: String, context: LuaBoot.Context) {
    do {
        let lifecycle = try LuaBoot.runSetup(L, setupPath: setupPath, context: context)
        evalfn = lifecycle.evalFunctionRef
        completionsForWordFn = lifecycle.completionsFunctionRef
        os_log(.default, "BREADCRUMB: setup.lua completed")
    } catch let error as LuaBoot.Error {
        terminateWithInitFailureAlert(error.description)
    } catch {
        terminateWithInitFailureAlert(String(describing: error))
    }
}

private func terminateWithInitFailureAlert(_ message: String) {
    os_log(.error, "%{public}s", message)
    let alert = NSAlert()
    alert.addButton(withTitle: "OK")
    alert.messageText = "Cosmic Hammer initialization failed"
    alert.informativeText = message
    alert.alertStyle = .critical
    alert.runModal()
    NSApplication.shared.terminate(nil)
}

// MARK: - Callbacks

private func currentLuaStateForCallback(_ callbackName: String) -> UnsafeMutablePointer<lua_State>? {
    guard let L = lua_getCurrentState() else {
        os_log(.debug, "Skipping %{public}s callback because Lua state is not available", callbackName)
        return nil
    }
    return L
}

/// Accessibility State Callback
@_cdecl("callAccessibilityStateCallback")
func callAccessibilityStateCallback() {
    guard let L = currentLuaStateForCallback("hs.accessibilityStateCallback") else { return }
    _lua_stackguard_entry(L)

    lua_getglobal(L, "hs")
    lua_getfield(L, -1, "accessibilityStateCallback")

    if lua_type(L, -1) == LUA_TNIL {
        // There is no callback set, so just pop the callback and carry on
        lua_pop(L, 1)
    } else {
        if lua_pcall(L, 0, 0, 0) != LUA_OK {
            let err = lua_tostring(L, -1).map { String(cString: $0) } ?? "(unknown)"
            os_log(.error, "hs.callAccessibilityStateCallback: %{public}s", err)
            lua_pop(L, 1)
        }
    }

    // Pop the hs global off the stack
    lua_pop(L, 1)
    _lua_stackguard_exit(L)
}

/// Text Dropped to Dock Icon Callback
@_cdecl("textDroppedToDockIcon")
func textDroppedToDockIcon(_ pboardString: NSString) {
    guard let L = currentLuaStateForCallback("hs.textDroppedToDockIconCallback") else { return }
    _lua_stackguard_entry(L)

    lua_getglobal(L, "hs")
    lua_getfield(L, -1, "textDroppedToDockIconCallback")

    if lua_type(L, -1) == LUA_TNIL {
        // There is no callback set, so just pop the callback and carry on
        lua_pop(L, 1)
    } else {
        lua_pushany(L, pboardString)
        if lua_pcall(L, 1, 0, 0) != LUA_OK {
            let err = lua_tostring(L, -1).map { String(cString: $0) } ?? "(unknown)"
            os_log(.error, "hs.textDroppedToDockIconCallback: %{public}s", err)
            lua_pop(L, 1)
        }
    }

    // Pop the hs global off the stack
    lua_pop(L, 1)
    _lua_stackguard_exit(L)
}

/// File Dropped to Dock Icon Callback
@_cdecl("fileDroppedToDockIcon")
func fileDroppedToDockIcon(_ filePath: NSString) {
    guard let L = currentLuaStateForCallback("hs.fileDroppedToDockIconCallback") else { return }
    _lua_stackguard_entry(L)

    lua_getglobal(L, "hs")
    lua_getfield(L, -1, "fileDroppedToDockIconCallback")

    if lua_type(L, -1) == LUA_TNIL {
        // There is no callback set, so just pop the callback and carry on
        lua_pop(L, 1)
    } else {
        lua_pushany(L, filePath)
        if lua_pcall(L, 1, 0, 0) != LUA_OK {
            let err = lua_tostring(L, -1).map { String(cString: $0) } ?? "(unknown)"
            os_log(.error, "hs.fileDroppedToDockIconCallback: %{public}s", err)
            lua_pop(L, 1)
        }
    }

    // Pop the hs global off the stack
    lua_pop(L, 1)
    _lua_stackguard_exit(L)
}

/// Dock Icon Click Callback
@_cdecl("callDockIconCallback")
func callDockIconCallback() {
    guard let L = currentLuaStateForCallback("hs.dockIconClickCallback") else { return }

    _lua_stackguard_entry(L)

    lua_getglobal(L, "hs")
    lua_getfield(L, -1, "dockIconClickCallback")

    if lua_type(L, -1) == LUA_TNIL {
        // There is no callback set, so just pop the callback and carry on
        lua_pop(L, 1)
    } else {
        if lua_pcall(L, 0, 0, 0) != LUA_OK {
            let err = lua_tostring(L, -1).map { String(cString: $0) } ?? "(unknown)"
            os_log(.error, "hs.dockIconClickCallback: %{public}s", err)
            lua_pop(L, 1)
        }
    }

    // Pop the hs global off the stack
    lua_pop(L, 1)
    _lua_stackguard_exit(L)
}

/// Shutdown Callback
private func callShutdownCallback(_ L: UnsafeMutablePointer<lua_State>!) {
    precondition(L != nil, "Lua state must not be nil for shutdown callback")
    _lua_stackguard_entry(L)

    lua_getglobal(L, "hs")
    lua_getfield(L, -1, "shutdownCallback")

    if lua_type(L, -1) == LUA_TNIL {
        // There is no callback set, so just pop the callback and carry on
        lua_pop(L, 1)
    } else {
        if lua_pcall(L, 0, 0, 0) != LUA_OK {
            let err = lua_tostring(L, -1).map { String(cString: $0) } ?? "(unknown)"
            os_log(.error, "hs.shutdownCallback: %{public}s", err)
            lua_pop(L, 1)
        }
    }

    // Pop the hs global off the stack
    lua_pop(L, 1)
    _lua_stackguard_exit(L)
}

/// Deconfigure a Lua environment that will shortly be destroyed
@_cdecl("MJLuaDeinit")
func MJLuaDeinit() {
    guard let L = lua_getCurrentState() else { return }

    callShutdownCallback(L)
    evalfn = LUA_NOREF
    completionsForWordFn = LUA_NOREF

    HSLoggerSetLuaState(MJLuaLogDelegate as AnyObject, nil)
}

/// Destroy a Lua environment
@_cdecl("MJLuaDealloc")
func MJLuaDealloc() {
    if let L = lua_getCurrentState() {
        environmentClearGlobal()

        // Bump generation BEFORE lua_close so async callbacks (which check
        // generation) bail out, but keep the state pointer alive because
        // synchronous GC finalizers (e.g. HSWebViewWindow.windowWillClose)
        // force-unwrap lua_getCurrentState() before their generation check.
        lua_bumpStateGeneration()

        // Save the Environment pointer from extra-space BEFORE lua_close frees
        // the lua_State memory. GC finalizers during lua_close can still read
        // the environment via the (not-yet-zeroed) extra-space slot.
        let extra = lua_getextraspace(L)!
        let envRaw = extra.load(as: UnsafeMutableRawPointer?.self)

        lua_close(L)

        // NOW nil the state — lua_close is done, no more finalizers running.
        lua_setCurrentState(nil)

        // Release the Environment from our saved pointer — NOT from the
        // now-freed lua_State. This was the crash: environmentDetach(L)
        // called lua_getextraspace on freed memory.
        if let raw = envRaw {
            Unmanaged<Environment>.fromOpaque(raw).release()
        }
    }
}

// MARK: - Run string / completions / get active state

@_cdecl("MJLuaRunString")
func MJLuaRunString(_ command: NSString) -> NSString {
    // Note: command can be empty (valid Lua noop); Swift's type system ensures non-nil.
    guard let L = currentLuaStateForCallback("MJLuaRunString") else { return "" }
    _lua_stackguard_entry(L)

    guard evalfn != LUA_NOREF else {
        os_log(.error, "ERROR: MJLuaRunString called before Lua lifecycle refs are available")
        _lua_stackguard_exit(L)
        return ""
    }

    lua_rawgeti(L, LUA_REGISTRYINDEX_VALUE, lua_Integer(evalfn))
    if !lua_isfunction(L, -1) {
        os_log(.error, "ERROR: MJLuaRunString doesn't seem to have an evalfn")
        if lua_isstring(L, -1) {
            os_log(.error, "evalfn appears to be a string: %{public}s", lua_tostring(L, -1).map { String(cString: $0) } ?? "")
        }
        // Whatever evalfn was, it wasn't a function, so pop it
        lua_pop(L, 1)
        _lua_stackguard_exit(L)
        return ""
    }
    lua_pushstring(L, (command as String).cString(using: .utf8))
    if lua_pcall(L, 1, 1, 0) != LUA_OK {
        if let errorMsg = lua_tostring(L, -1) {
            os_log(.error, "%{public}s", String(cString: errorMsg))
        }
    }

    var len: Int = 0
    let s = lua_tolstring(L, -1, &len)
    var str: NSString
    if let s = s, let converted = String(data: Data(bytes: s, count: len), encoding: .utf8) {
        str = converted as NSString
    } else if let s = s {
        str = getValidUTF8(s, ofLength: len) as NSString
    } else {
        str = ""
    }
    lua_pop(L, 1)

    _lua_stackguard_exit(L)
    return str
}

@_cdecl("MJLuaCompletionsForWord")
func MJLuaCompletionsForWord(_ completionWord: NSString) -> NSArray {
    // Note: completionWord can be empty (prefix matching); Swift's type system ensures non-nil.
    guard let L = currentLuaStateForCallback("MJLuaCompletionsForWord") else { return [] }
    _lua_stackguard_entry(L)

    guard completionsForWordFn != LUA_NOREF else {
        os_log(.error, "ERROR: MJLuaCompletionsForWord called before Lua lifecycle refs are available")
        _lua_stackguard_exit(L)
        return []
    }

    lua_rawgeti(L, LUA_REGISTRYINDEX_VALUE, lua_Integer(completionsForWordFn))
    lua_pushany(L, completionWord)
    if lua_pcall(L, 1, 1, 0) != LUA_OK {
        let err = lua_tostring(L, -1).map { String(cString: $0) } ?? "(unknown)"
        os_log(.error, "MJLuaCompletionsForWord: %{public}s", err)
        lua_pop(L, 1)
        _lua_stackguard_exit(L)
        return []
    }

    let completions = lua_tovalue(L, at: -1) as? [Any] ?? []
    lua_pop(L, 1)
    _lua_stackguard_exit(L)
    return completions as NSArray
}

/// C-Code helper to return current active LuaState. Useful for callbacks to
/// verify stored LuaState still matches active one if GC fails to clear it.
@_cdecl("MJGetActiveLuaState")
func MJGetActiveLuaState() -> UnsafeMutablePointer<lua_State>? {
    return lua_getCurrentState()
}
