import Cocoa
import LuaSkin

private let USERDATA_TAG = "hs.dialog"
private var refTable: LSRefTable = LUA_NOREF

// MARK: - Support Functions and Classes

//
// COLOR PANEL:
//
private class HSColorPanel: NSObject {
    var callbackRef: Int32 = LUA_NOREF

    override init() {
        super.init()
        let cp = NSColorPanel.shared
        cp.setTarget(self)
        cp.setAction(#selector(colorCallback(_:)))

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(colorClose(_:)),
            name: NSWindow.willCloseNotification,
            object: cp
        )
    }

    // Second argument to callback is true indicating this is a close color panel event
    @objc func colorClose(_ note: NSNotification) {
        if callbackRef != LUA_NOREF {
            DispatchQueue.main.async { [weak self] in
                guard let self = self, self.callbackRef != LUA_NOREF else { return }
                let skin = LuaSkin.skin(with: nil)
                _lua_stackguard_entry(skin.l)
                let L = skin.l!
                let cp = NSColorPanel.shared
                skin.pushLuaRef(refTable, ref: self.callbackRef)
                skin.pushNSObject(cp.color)
                lua_pushboolean(L, 1)
                skin.protectedCallAndError("hs.dialog color close callback", nargs: 2, nresults: 0)
                _lua_stackguard_exit(skin.l)
            }
        }
    }

    // Second argument to callback is false indicating that the color panel is still open (i.e. they may change color again)
    @objc func colorCallback(_ colorPanel: NSColorPanel) {
        if callbackRef != LUA_NOREF {
            DispatchQueue.main.async { [weak self] in
                guard let self = self, self.callbackRef != LUA_NOREF else { return }
                let skin = LuaSkin.skin(with: nil)
                _lua_stackguard_entry(skin.l)
                let L = skin.l!
                skin.pushLuaRef(refTable, ref: self.callbackRef)
                skin.pushNSObject(colorPanel.color)
                lua_pushboolean(L, 0)
                skin.protectedCallAndError("hs.dialog color callback", nargs: 2, nresults: 0)
                _lua_stackguard_exit(skin.l)
            }
        }
    }
}

private var cpReceiverObject: HSColorPanel?

// MARK: - Color Panel Functions

/// hs.dialog.color.callback([callbackFn]) -> function or nil
/// Function
/// Sets or removes the callback function for the color panel.
///
/// Parameters:
///  * a function, or `nil` to remove the current function, which will be invoked as a callback for messages generated by this color panel. The callback function should expect 2 arguments as follows:
///    ** A table containing the color values from the color panel.
///    ** A boolean which returns `true` if the color panel has been closed otherwise `false` indicating that the color panel is still open (i.e. it may change color again).
///
/// Returns:
///  * The last callbackFn or `nil` so you can save it and re-attach it if something needs to temporarily take the callbacks.
///
/// Notes:
///  * Example:
///      `hs.dialog.color.callback(function(a,b) print("COLOR CALLBACK:\nSelected Color: " .. hs.inspect(a) .. "\nPanel Closed: " .. hs.inspect(b)) end)`
private func colorPanelCallback(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let skin = LuaSkin.skin(with: L)
    skin.checkArgs(LS_TFUNCTION | LS_TNIL | LS_TOPTIONAL, LS_TBREAK)

    if cpReceiverObject!.callbackRef != LUA_NOREF {
        skin.pushLuaRef(refTable, ref: cpReceiverObject!.callbackRef)
    } else {
        lua_pushnil(L)
    }
    if lua_gettop(L) == 2 { // we just added to it...
        // in either case, we need to remove an existing callback, so...
        cpReceiverObject!.callbackRef = skin.luaUnref(refTable, ref: cpReceiverObject!.callbackRef)
        if lua_type(L, 1) == LUA_TFUNCTION {
            lua_pushvalue(L, 1)
            cpReceiverObject!.callbackRef = skin.luaRef(refTable)
        }
    }
    // return the *last* fn (or nil) so you can save it and re-attach it if something needs to
    // temporarily take the callbacks
    return 1
}

/// hs.dialog.color.continuous([value]) -> boolean
/// Function
/// Set or display whether or not the callback should be continuously updated when a user drags a color slider or control.
///
/// Parameters:
///  * [value] - `true` if you want to continuously trigger the callback, otherwise `false`.
///
/// Returns:
///  * `true` if continuous is enabled otherwise `false`
///
/// Notes:
///  * Example:
///      `hs.dialog.color.continuous(true)`
private func colorPanelContinuous(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let skin = LuaSkin.skin(with: L)
    skin.checkArgs(LS_TBOOLEAN | LS_TOPTIONAL, LS_TBREAK)
    let cp = NSColorPanel.shared
    if lua_gettop(L) == 1 {
        cp.isContinuous = lua_toboolean(L, 1) != 0
    }
    lua_pushboolean(L, cp.isContinuous ? 1 : 0)
    return 1
}

/// hs.dialog.color.showsAlpha([value]) -> boolean
/// Function
/// Set or display whether or not the color panel should display an opacity slider.
///
/// Parameters:
///  * [value] - `true` if you want to display an opacity slider, otherwise `false`.
///
/// Returns:
///  * `true` if the opacity slider is displayed otherwise `false`
///
/// Notes:
///  * Example:
///      `hs.dialog.color.showsAlpha(true)`
private func colorPanelShowsAlpha(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let skin = LuaSkin.skin(with: L)
    skin.checkArgs(LS_TBOOLEAN | LS_TOPTIONAL, LS_TBREAK)
    let cp = NSColorPanel.shared
    if lua_gettop(L) == 1 {
        cp.showsAlpha = lua_toboolean(L, 1) != 0
    }
    lua_pushboolean(L, cp.showsAlpha ? 1 : 0)
    return 1
}

/// hs.dialog.color.color([value]) -> table
/// Function
/// Set or display the currently selected color in a color wheel.
///
/// Parameters:
///  * [value] - The color values in a table (as described in `hs.drawing.color`).
///
/// Returns:
///  * A table of the currently selected color in the form of `hs.drawing.color`.
///
/// Notes:
///  * Example:
///      `hs.dialog.color.color(hs.drawing.color.blue)`
private func colorPanelColor(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let skin = LuaSkin.skin(with: L)
    skin.checkArgs(LS_TTABLE | LS_TOPTIONAL, LS_TBREAK)
    let cp = NSColorPanel.shared
    if lua_gettop(L) == 1 {
        let theColor = skin.luaObject(at: 1, toClass: "NSColor") as! NSColor
        cp.color = theColor
    }
    skin.pushNSObject(cp.color)
    return 1
}

/// hs.dialog.color.mode([value]) -> table
/// Function
/// Set or display the currently selected color panel mode.
///
/// Parameters:
///  * [value] - The mode you wish to use as a string from the following options:
///    ** "wheel" - Color Wheel
///    ** "gray" - Gray Scale Slider
///    ** "RGB" - RGB Sliders
///    ** "CMYK" - CMYK Sliders
///    ** "HSB" - HSB Sliders
///    ** "list" - Color Palettes
///    ** "custom" - Image Palettes
///    ** "crayon" - Pencils
///    ** "none"
///
/// Returns:
///  * The current mode as a string.
///
/// Notes:
///  * Example:
///      `hs.dialog.color.mode("RGB")`
private func colorPanelMode(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let skin = LuaSkin.skin(with: L)
    skin.checkArgs(LS_TSTRING | LS_TOPTIONAL, LS_TBREAK)
    let cp = NSColorPanel.shared
    if lua_gettop(L) == 1 {
        let theMode = skin.toNSObject(atIndex: 1) as! String
        switch theMode {
        case "none":   cp.mode = .none
        case "gray":   cp.mode = .gray
        case "RGB":    cp.mode = .RGB
        case "CMYK":   cp.mode = .CMYK
        case "HSB":    cp.mode = .HSB
        case "custom": cp.mode = .customPalette
        case "list":   cp.mode = .colorList
        case "wheel":  cp.mode = .wheel
        case "crayon": cp.mode = .crayon
        default:
            return luaL_error(L, "unknown color panel mode")
        }
    }

    switch cp.mode {
    case .none:          skin.pushNSObject("none")
    case .gray:          skin.pushNSObject("gray")
    case .RGB:           skin.pushNSObject("RGB")
    case .CMYK:          skin.pushNSObject("CMYK")
    case .HSB:           skin.pushNSObject("HSB")
    case .customPalette: skin.pushNSObject("custom")
    case .colorList:     skin.pushNSObject("list")
    case .wheel:         skin.pushNSObject("wheel")
    case .crayon:        skin.pushNSObject("crayon")
    default:
        skin.pushNSObject("** unrecognized mode:\(cp.mode.rawValue)")
    }
    return 1
}

/// hs.dialog.color.alpha([value]) -> number
/// Function
/// Set or display the selected opacity.
///
/// Parameters:
///  * [value] - A opacity value as a number between 0 and 1, where 0 is 100% transparent/see-through.
///
/// Returns:
///  * The current alpha value as a number.
///
/// Notes:
///  * Example:
///      `hs.dialog.color.alpha(0.5)`
private func colorPanelAlpha(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let skin = LuaSkin.skin(with: L)
    skin.checkArgs(LS_TNUMBER | LS_TOPTIONAL, LS_TBREAK)

    let cp = NSColorPanel.shared
    if lua_gettop(L) == 1 {
        let alpha = skin.toNSObject(atIndex: 1) as! NSNumber
        let color = cp.color.withAlphaComponent(CGFloat(alpha.doubleValue))
        cp.color = color
    }

    lua_pushnumber(L, lua_Number(NSColorPanel.shared.alpha))
    return 1
}

/// hs.dialog.color.show() -> none
/// Function
/// Shows the Color Panel.
///
/// Parameters:
///  * None
///
/// Returns:
///  * None
///
/// Notes:
///  * Example:
///      `hs.dialog.color.show()`
private func colorPanelShow(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let skin = LuaSkin.skin(with: L)
    skin.checkArgs(LS_TBREAK)
    NSApp.orderFrontColorPanel(nil)
    return 0
}

/// hs.dialog.color.hide() -> none
/// Function
/// Hides the Color Panel.
///
/// Parameters:
///  * None
///
/// Returns:
///  * None
///
/// Notes:
///  * Example:
///      `hs.dialog.color.hide()`
private func colorPanelHide(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let skin = LuaSkin.skin(with: L)
    skin.checkArgs(LS_TBREAK)
    NSColorPanel.shared.close()
    return 0
}

// MARK: - Choose File or Folder

/// hs.dialog.chooseFileOrFolder([message], [defaultPath], [canChooseFiles], [canChooseDirectories], [allowsMultipleSelection], [allowedFileTypes], [resolvesAliases]) -> string
/// Function
/// Displays a file and/or folder selection dialog box using NSOpenPanel.
///
/// Parameters:
///  * [message] - The optional message text to display.
///  * [defaultPath] - The optional path you want to dialog to open to.
///  * [canChooseFiles] - Whether or not the user can select files. Defaults to `true`.
///  * [canChooseDirectories] - Whether or not the user can select folders. Default to `false`.
///  * [allowsMultipleSelection] - Allow multiple selections of files and/or folders. Defaults to `false`.
///  * [allowedFileTypes] - An optional table of allowed file types. Defaults to `true`.
///  * [resolvesAliases] - An optional boolean that indicates whether the panel resolves aliases.
///
/// Returns:
///  * The selected files in a table or `nil` if cancel was pressed.
///
/// Notes:
///  * The optional values must be entered in order (i.e. you can't supply `allowsMultipleSelection` without also supplying `canChooseFiles` and `canChooseDirectories`).
///  * Example:
///      `hs.inspect(hs.dialog.chooseFileOrFolder("Please select a file:", "~/Desktop", true, false, true, {"jpeg", "pdf"}, true))`
private func chooseFileOrFolder(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    // Check the Parameters:
    let skin = LuaSkin.skin(with: L)
    //              [message],                 [defaultPath],             [canChooseFiles],           [canChooseDirectories],     [allowsMultipleSelection],  [allowedFileTypes],       [resolvesAliases]
    skin.checkArgs(LS_TOPTIONAL | LS_TSTRING, LS_TOPTIONAL | LS_TSTRING, LS_TBOOLEAN | LS_TOPTIONAL, LS_TBOOLEAN | LS_TOPTIONAL, LS_TBOOLEAN | LS_TOPTIONAL, LS_TTABLE | LS_TOPTIONAL, LS_TBOOLEAN | LS_TOPTIONAL, LS_TBREAK)

    // Create new NSOpenPanel:
    let panel = NSOpenPanel()

    // Allowed File Types:
    if lua_istable(L, 6) {
        var allowedFileTypes: [String] = []
        lua_pushnil(L)
        while lua_next(L, 6) != 0 {
            let item = String(cString: luaL_checkstring(L, -1))
            allowedFileTypes.append(item)
            lua_pop(L, 1)
        }
        panel.allowedFileTypes = allowedFileTypes
    }

    // Message:
    if let message = skin.toNSObject(atIndex: 1) as? String {
        panel.message = message
    }

    // Default Path:
    if let path = skin.toNSObject(atIndex: 2) as? String {
        panel.directoryURL = URL(fileURLWithPath: path)
    }

    // Can Choose Files:
    panel.canChooseFiles = !(lua_isboolean(L, 3) && lua_toboolean(L, 3) == 0)

    // Can Choose Directories:
    panel.canChooseDirectories = lua_isboolean(L, 4) && lua_toboolean(L, 4) != 0

    // Resolve Aliases:
    panel.resolvesAliases = lua_isboolean(L, 7) && lua_toboolean(L, 7) != 0

    // Allows Multiple Selections:
    panel.allowsMultipleSelection = !(lua_isboolean(L, 5) && lua_toboolean(L, 5) == 0)

    // Load the window and check to see when a button is clicked:
    let clicked = panel.runModal()

    if clicked == .OK {
        lua_newtable(L)
        var count: Int32 = 1
        for url in panel.urls {
            lua_pushstring(L, url.path)
            lua_setfield(L, -2, "\(count)")
            count += 1
        }
    } else {
        lua_pushnil(L)
    }

    return 1
}

// MARK: - Webview Alert

/// hs.dialog.webviewAlert(webview, callbackFn, message, [informativeText], [buttonOne], [buttonTwo], [style]) -> string
/// Function
/// Displays a simple dialog box using `NSAlert` in a `hs.webview`.
///
/// Parameters:
///  * webview - The `hs.webview` to display the alert on.
///  * callbackFn - The callback function that's called when a button is pressed.
///  * message - The message text to display.
///  * [informativeText] - Optional informative text to display.
///  * [buttonOne] - An optional value for the first button as a string. Defaults to "OK".
///  * [buttonTwo] - An optional value for the second button as a string. If `nil` is used, no second button will be displayed.
///  * [style] - An optional style of the dialog box as a string. Defaults to "warning".
///
/// Returns:
///  * nil
///
/// Notes:
///  * This alert is will prevent the user from interacting with the `hs.webview` until a button is pressed on the alert.
///  * The optional values must be entered in order (i.e. you can't supply `style` without also supplying `buttonOne` and `buttonTwo`).
///  * [style] can be "warning", "informational" or "critical". If something other than these string values is given, it will use "informational".
///  * Example:
///      ```lua
///      testCallbackFn = function(result) print("Callback Result: " .. result) end
///      testWebviewA = hs.webview.newBrowser(hs.geometry.rect(250, 250, 250, 250)):show()
///      testWebviewB = hs.webview.newBrowser(hs.geometry.rect(450, 450, 450, 450)):show()
///      hs.dialog.webviewAlert(testWebviewA, testCallbackFn, "Message", "Informative Text", "Button One", "Button Two", "warning")
///      hs.dialog.webviewAlert(testWebviewB, testCallbackFn, "Message", "Informative Text", "Single Button")```
private func webviewAlert(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let defaultButton = "OK"
    let defaultAlertStyle = NSAlert.Style.informational

    let skin = LuaSkin.skin(with: L)
    //                            webview,      callbackFn,   message,    [informativeText],         [buttonOne],               [buttonTwo],                         [style]
    skin.checkArgs(LS_TUSERDATA, "hs.webview", LS_TFUNCTION, LS_TSTRING, LS_TSTRING | LS_TOPTIONAL, LS_TSTRING | LS_TOPTIONAL, LS_TSTRING | LS_TNIL | LS_TOPTIONAL, LS_TSTRING | LS_TOPTIONAL, LS_TBREAK)

    let webview = skin.toNSObject(atIndex: 1) as! NSWindow

    lua_pushvalue(L, 2) // Copy the callback function to the top of the stack
    var callbackRef = skin.luaRef(refTable) // Store what's at the top of the stack in the registry

    let message = skin.toNSObject(atIndex: 3) as! String
    let informativeText = skin.toNSObject(atIndex: 4) as? String
    let buttonOne = skin.toNSObject(atIndex: 5) as? String
    let buttonTwo = skin.toNSObject(atIndex: 6) as? String
    let style = skin.toNSObject(atIndex: 7) as? String

    let alert = NSAlert()
    alert.messageText = message

    if let informativeText = informativeText {
        alert.informativeText = informativeText
    }

    if let buttonOne = buttonOne, !buttonOne.isEmpty {
        alert.addButton(withTitle: buttonOne)
    } else {
        alert.addButton(withTitle: defaultButton)
    }

    if let buttonTwo = buttonTwo, !buttonTwo.isEmpty {
        alert.addButton(withTitle: buttonTwo)
    }

    switch style {
    case "warning":       alert.alertStyle = .warning
    case "informational": alert.alertStyle = .informational
    case "critical":      alert.alertStyle = .critical
    default:              alert.alertStyle = defaultAlertStyle
    }

    alert.beginSheetModal(for: webview) { result in
        var button = defaultButton

        if result == .alertFirstButtonReturn {
            if let buttonOne = buttonOne {
                button = buttonOne
            }
        } else if result == .alertSecondButtonReturn {
            button = buttonTwo ?? defaultButton
        } else {
            skin.logError("hs.dialog.webviewAlert() - Failed to detect which button was pressed.")
            lua_pushnil(L)
        }

        skin.pushLuaRef(refTable, ref: callbackRef) // Put the saved function back on the stack.
        callbackRef = skin.luaUnref(refTable, ref: callbackRef) // Remove the stored function from the registry.
        skin.pushNSObject(button)
        skin.protectedCallAndError("hs.dialog:callback", nargs: 1, nresults: 0)
    }

    lua_pushnil(L)
    return 1
}

// MARK: - Blocking Alert

/// hs.dialog.blockAlert(message, informativeText, [buttonOne], [buttonTwo], [style]) -> string
/// Function
/// Displays a simple dialog box using `NSAlert` that will halt Lua code processing until the alert is closed.
///
/// Parameters:
///  * message - The message text to display.
///  * informativeText - The informative text to display.
///  * [buttonOne] - An optional value for the first button as a string. Defaults to "OK".
///  * [buttonTwo] - An optional value for the second button as a string. If `nil` is used, no second button will be displayed.
///  * [style] - An optional style of the dialog box as a string. Defaults to "informational".
///
/// Returns:
///  * The value of the button as a string.
///
/// Notes:
///  * The optional values must be entered in order (i.e. you can't supply `style` without also supplying `buttonOne` and `buttonTwo`).
///  * [style] can be "warning", "informational" or "critical". If something other than these string values is given, it will use "warning".
///  * Example:
///      `hs.dialog.blockAlert("Message", "Informative Text", "Button One", "Button Two", "critical")`
private func blockAlert(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let defaultButton = "OK"

    let skin = LuaSkin.skin(with: L)
    //              message,    informativeText,
    //                                      [buttonOne],               [buttonTwo],               [style]
    skin.checkArgs(LS_TSTRING, LS_TSTRING, LS_TSTRING | LS_TOPTIONAL, LS_TSTRING | LS_TOPTIONAL, LS_TSTRING | LS_TOPTIONAL, LS_TBREAK)

    let message = skin.toNSObject(atIndex: 1) as! String
    let informativeText = skin.toNSObject(atIndex: 2) as! String
    let buttonOne = skin.toNSObject(atIndex: 3) as? String
    let buttonTwo = skin.toNSObject(atIndex: 4) as? String
    let style = skin.toNSObject(atIndex: 5) as? String

    let alert = NSAlert()
    alert.messageText = message
    alert.informativeText = informativeText

    if let buttonOne = buttonOne, !buttonOne.isEmpty {
        alert.addButton(withTitle: buttonOne)
    } else {
        alert.addButton(withTitle: defaultButton)
    }

    if let buttonTwo = buttonTwo, !buttonTwo.isEmpty {
        alert.addButton(withTitle: buttonTwo)
    }

    switch style {
    case "warning":       alert.alertStyle = .warning
    case "informational": alert.alertStyle = .informational
    case "critical":      alert.alertStyle = .critical
    default:              alert.alertStyle = .warning
    }

    let result = alert.runModal()

    if result == .alertFirstButtonReturn {
        if buttonOne == nil {
            lua_pushstring(L, defaultButton)
        } else {
            lua_pushvalue(L, 3)
        }
    } else if result == .alertSecondButtonReturn {
        lua_pushvalue(L, 4)
    } else {
        skin.logError("hs.dialog.alert() - Failed to detect which button was pressed.")
        lua_pushnil(L)
    }

    return 1
}

// MARK: - Text Prompt

/// hs.dialog.textPrompt(message, informativeText, [defaultText], [buttonOne], [buttonTwo], [secureField]) -> string, string
/// Function
/// Displays a simple text input dialog box.
///
/// Parameters:
///  * message - The message text to display
///  * informativeText - The informative text to display
///  * [defaultText] - The informative text to display
///  * [buttonOne] - An optional value for the first button as a string
///  * [buttonTwo] - An optional value for the second button as a string
///  * [secureField] - An optional boolean. If true, PasswordField instead of TextField. Defaults to false.
///
/// Returns:
///  * The value of the button as a string
///  * The value of the text input as a string
///
/// Notes:
///  * `buttonOne` defaults to "OK" if no value is supplied.
///  * `buttonOne` will also be triggered by pressing `ENTER`, whereas `buttonTwo` will be triggered by pressing `ESC`.
///  * Examples:
///      `hs.dialog.textPrompt("Main message.", "Please enter something:")`
///      `hs.dialog.textPrompt("Main message.", "Please enter something:", "Default Value", "OK")`
///      `hs.dialog.textPrompt("Main message.", "Please enter something:", "Default Value", "OK", "Cancel")`
///      `hs.dialog.textPrompt("Main message.", "Please enter something:", "", "OK", "Cancel", true)`
private func textPrompt(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let defaultButton = "OK"

    let skin = LuaSkin.skin(with: L)
    //              message,    informativeText,
    //                                      [defaultText],             [buttonOne],               [buttonTwo]
    skin.checkArgs(LS_TSTRING, LS_TSTRING, LS_TSTRING | LS_TOPTIONAL, LS_TSTRING | LS_TOPTIONAL, LS_TSTRING | LS_TOPTIONAL, LS_TBOOLEAN | LS_TOPTIONAL, LS_TBREAK)

    let message = skin.toNSObject(atIndex: 1) as! String
    let informativeText = skin.toNSObject(atIndex: 2) as! String
    let defaultText = skin.toNSObject(atIndex: 3) as? String
    let buttonOne = skin.toNSObject(atIndex: 4) as? String
    let buttonTwo = skin.toNSObject(atIndex: 5) as? String
    let secureField = (lua_type(L, 6) == LUA_TBOOLEAN) ? (lua_toboolean(L, 6) != 0) : false

    let alert = NSAlert()
    alert.messageText = message
    alert.informativeText = informativeText

    if let buttonOne = buttonOne, !buttonOne.isEmpty {
        alert.addButton(withTitle: buttonOne)
    } else {
        alert.addButton(withTitle: defaultButton)
    }

    if let buttonTwo = buttonTwo, !buttonTwo.isEmpty {
        alert.addButton(withTitle: buttonTwo)
        alert.buttons[1].keyEquivalent = "\u{1b}" // Escape
        alert.buttons[0].keyEquivalent = "\r"       // Return
    } else {
        alert.buttons[0].keyEquivalent = "\r" // Return
    }

    let input: NSTextField
    if secureField {
        input = NSSecureTextField(frame: NSMakeRect(0, 0, 200, 24))
    } else {
        input = NSTextField(frame: NSMakeRect(0, 0, 200, 24))
    }

    input.stringValue = defaultText ?? ""

    alert.accessoryView = input

    // Focus on text input:
    alert.window.initialFirstResponder = input

    // Show alert:
    let result = alert.runModal()

    if result == .alertFirstButtonReturn {
        if buttonOne == nil {
            lua_pushstring(L, defaultButton)
            lua_pushstring(L, input.stringValue)
        } else {
            lua_pushvalue(L, 4)
            lua_pushstring(L, input.stringValue)
        }
    } else if result == .alertSecondButtonReturn {
        lua_pushvalue(L, 5)
        lua_pushstring(L, input.stringValue)
    } else {
        skin.logError("hs.dialog.textPrompt() - Failed to detect which button was pressed.")
        lua_pushnil(L)
    }

    return 2
}

// MARK: - Cosmic Hammer/Lua Infrastructure

private func releaseReceivers(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let skin = LuaSkin.skin(with: L)
    let cp = NSColorPanel.shared
    NotificationCenter.default.removeObserver(
        cpReceiverObject!,
        name: NSWindow.willCloseNotification,
        object: cp
    )
    cp.setTarget(nil)
    cp.setAction(nil)
    if cpReceiverObject!.callbackRef != LUA_NOREF {
        let _ = skin.luaUnref(refTable, ref: cpReceiverObject!.callbackRef)
    }
    cp.close() // Close the Color Panel
    cpReceiverObject = nil

    return 0
}

// Functions for returned object when module loads:
private var moduleLib: [luaL_Reg] = [
    luaL_Reg(name: strdup("webviewAlert"), func: webviewAlert),
    luaL_Reg(name: strdup("blockAlert"), func: blockAlert),
    luaL_Reg(name: strdup("textPrompt"), func: textPrompt),
    luaL_Reg(name: strdup("chooseFileOrFolder"), func: chooseFileOrFolder),
    luaL_Reg(name: nil, func: nil),
]

private var colorPanelLib: [luaL_Reg] = [
    luaL_Reg(name: strdup("alpha"), func: colorPanelAlpha),
    luaL_Reg(name: strdup("callback"), func: colorPanelCallback),
    luaL_Reg(name: strdup("color"), func: colorPanelColor),
    luaL_Reg(name: strdup("continuous"), func: colorPanelContinuous),
    luaL_Reg(name: strdup("mode"), func: colorPanelMode),
    luaL_Reg(name: strdup("showsAlpha"), func: colorPanelShowsAlpha),
    luaL_Reg(name: strdup("show"), func: colorPanelShow),
    luaL_Reg(name: strdup("hide"), func: colorPanelHide),
    luaL_Reg(name: nil, func: nil),
]

private var module_metaLib: [luaL_Reg] = [
    luaL_Reg(name: strdup("__gc"), func: releaseReceivers),
    luaL_Reg(name: nil, func: nil),
]

@_cdecl("luaopen_hs_libdialog")
public func luaopen_hs_libdialog(_ L: UnsafeMutablePointer<lua_State>!) -> Int32 {
    let skin = LuaSkin.skin(with: L)
    refTable = skin.registerLibrary(USERDATA_TAG, functions: &moduleLib, metaFunctions: &module_metaLib)

    lua_newtable(L)
    luaL_setfuncs(L, &colorPanelLib, 0)
    lua_setfield(L, -2, "color")
    NSColorPanel.setPickerMask(NSColorPanel.Options(rawValue: 0xFFFF))
    cpReceiverObject = HSColorPanel()

    return 1
}
