-- AUTO-GENERATED. DO NOT EDIT. Re-run scripts/generate-hsextensions.sh.
--
-- Loader metadata generated from extensions.manifest. App bootstrap, test
-- bootstrap, preload aliases, lazy loading, and Lua resource copying all
-- consume this manifest-derived shape.

local M = {}

M.nativeModules = {
  ["hs.libapplication"] = { symbol = "luaopen_hs_libapplication" },
  ["hs.libapplicationwatcher"] = { symbol = "luaopen_hs_libapplicationwatcher" },
  ["hs.libaudiodevice"] = { symbol = "luaopen_hs_libaudiodevice" },
  ["hs.libaudiodevicewatcher"] = { symbol = "luaopen_hs_libaudiodevicewatcher" },
  ["hs.libaxuielement"] = { symbol = "luaopen_hs_libaxuielement" },
  ["hs.libbase64"] = { symbol = "luaopen_hs_libbase64" },
  ["hs.libbattery"] = { symbol = "luaopen_hs_libbattery" },
  ["hs.libbatterywatcher"] = { symbol = "luaopen_hs_libbatterywatcher" },
  ["hs.libbonjour"] = { symbol = "luaopen_hs_libbonjour" },
  ["hs.libbonjourservice"] = { symbol = "luaopen_hs_libbonjourservice" },
  ["hs.libbrightness"] = { symbol = "luaopen_hs_libbrightness" },
  ["hs.libcaffeinate"] = { symbol = "luaopen_hs_libcaffeinate" },
  ["hs.libcaffeinatewatcher"] = { symbol = "luaopen_hs_libcaffeinatewatcher" },
  ["hs.libcamera"] = { symbol = "luaopen_hs_libcamera" },
  ["hs.libcanvas"] = { symbol = "luaopen_hs_libcanvas" },
  ["hs.libcanvasmatrix"] = { symbol = "luaopen_hs_libcanvasmatrix" },
  ["hs.libchooser"] = { symbol = "luaopen_hs_libchooser" },
  ["hs.libconsole"] = { symbol = "luaopen_hs_libconsole" },
  ["hs.libcrash"] = { symbol = "luaopen_hs_libcrash" },
  ["hs.libdialog"] = { symbol = "luaopen_hs_libdialog" },
  ["hs.libdistributednotifications"] = { symbol = "luaopen_hs_libdistributednotifications" },
  ["hs.libdoc"] = { symbol = "luaopen_hs_libdoc" },
  ["hs.libdockicon"] = { symbol = "luaopen_hs_libdockicon" },
  ["hs.libdrawing_color"] = { symbol = "luaopen_hs_libdrawing_color" },
  ["hs.libeventtap"] = { symbol = "luaopen_hs_libeventtap" },
  ["hs.libeventtapevent"] = { symbol = "luaopen_hs_libeventtapevent" },
  ["hs.libfs"] = { symbol = "luaopen_hs_libfs" },
  ["hs.libfsvolume"] = { symbol = "luaopen_hs_libfsvolume" },
  ["hs.libfsxattr"] = { symbol = "luaopen_hs_libfsxattr" },
  ["hs.libhash"] = { symbol = "luaopen_hs_libhash" },
  ["hs.libhid"] = { symbol = "luaopen_hs_libhid" },
  ["hs.libhints"] = { symbol = "luaopen_hs_libhints" },
  ["hs.libhost"] = { symbol = "luaopen_hs_libhost" },
  ["hs.libhost_locale"] = { symbol = "luaopen_hs_libhost_locale" },
  ["hs.libhotkey"] = { symbol = "luaopen_hs_libhotkey" },
  ["hs.libhttp"] = { symbol = "luaopen_hs_libhttp" },
  ["hs.libhttpserver"] = { symbol = "luaopen_hs_libhttpserver" },
  ["hs.libimage"] = { symbol = "luaopen_hs_libimage" },
  ["hs.libipc"] = { symbol = "luaopen_hs_libipc" },
  ["hs.libjson"] = { symbol = "luaopen_hs_libjson" },
  ["hs.libkeycodes"] = { symbol = "luaopen_hs_libkeycodes" },
  ["hs.liblocation"] = { symbol = "luaopen_hs_liblocation" },
  ["hs.liblsqlite3"] = { symbol = "luaopen_hs_liblsqlite3" },
  ["hs.libmarkdown"] = { symbol = "luaopen_hs_libmarkdown" },
  ["hs.libmath"] = { symbol = "luaopen_hs_libmath" },
  ["hs.libmenubar"] = { symbol = "luaopen_hs_libmenubar" },
  ["hs.libmidi"] = { symbol = "luaopen_hs_libmidi" },
  ["hs.libmilight"] = { symbol = "luaopen_hs_libmilight" },
  ["hs.libmouse"] = { symbol = "luaopen_hs_libmouse" },
  ["hs.libnetworkconfiguration"] = { symbol = "luaopen_hs_libnetworkconfiguration" },
  ["hs.libnetworkhost"] = { symbol = "luaopen_hs_libnetworkhost" },
  ["hs.libnetworkping"] = { symbol = "luaopen_hs_libnetworkping" },
  ["hs.libnetworkreachability"] = { symbol = "luaopen_hs_libnetworkreachability" },
  ["hs.libnoises"] = { symbol = "luaopen_hs_libnoises" },
  ["hs.libnotify"] = { symbol = "luaopen_hs_libnotify" },
  ["hs.libosascript"] = { symbol = "luaopen_hs_libosascript" },
  ["hs.libpasteboard"] = { symbol = "luaopen_hs_libpasteboard" },
  ["hs.libpasteboardwatcher"] = { symbol = "luaopen_hs_libpasteboardwatcher" },
  ["hs.libpathwatcher"] = { symbol = "luaopen_hs_libpathwatcher" },
  ["hs.libplist"] = { symbol = "luaopen_hs_libplist" },
  ["hs.librazer"] = { symbol = "luaopen_hs_librazer" },
  ["hs.libscreen"] = { symbol = "luaopen_hs_libscreen" },
  ["hs.libscreenwatcher"] = { symbol = "luaopen_hs_libscreenwatcher" },
  ["hs.libserial"] = { symbol = "luaopen_hs_libserial" },
  ["hs.libsettings"] = { symbol = "luaopen_hs_libsettings" },
  ["hs.libsharing"] = { symbol = "luaopen_hs_libsharing" },
  ["hs.libshortcuts"] = { symbol = "luaopen_hs_libshortcuts" },
  ["hs.libsocket"] = { symbol = "luaopen_hs_libsocket" },
  ["hs.libsocketudp"] = { symbol = "luaopen_hs_libsocketudp" },
  ["hs.libsound"] = { symbol = "luaopen_hs_libsound" },
  ["hs.libspaces"] = { symbol = "luaopen_hs_libspaces" },
  ["hs.libspaces_watcher"] = { symbol = "luaopen_hs_libspaces_watcher" },
  ["hs.libspeech"] = { symbol = "luaopen_hs_libspeech" },
  ["hs.libspeechlistener"] = { symbol = "luaopen_hs_libspeechlistener" },
  ["hs.libspotlight"] = { symbol = "luaopen_hs_libspotlight" },
  ["hs.libstreamdeck"] = { symbol = "luaopen_hs_libstreamdeck" },
  ["hs.libstyledtext"] = { symbol = "luaopen_hs_libstyledtext" },
  ["hs.libtask"] = { symbol = "luaopen_hs_libtask" },
  ["hs.libtimer"] = { symbol = "luaopen_hs_libtimer" },
  ["hs.libuielement"] = { symbol = "luaopen_hs_libuielement" },
  ["hs.libuielementwatcher"] = { symbol = "luaopen_hs_libuielementwatcher" },
  ["hs.liburlevent"] = { symbol = "luaopen_hs_liburlevent" },
  ["hs.libusb"] = { symbol = "luaopen_hs_libusb" },
  ["hs.libusbwatcher"] = { symbol = "luaopen_hs_libusbwatcher" },
  ["hs.libwebsocket"] = { symbol = "luaopen_hs_libwebsocket" },
  ["hs.libwebview"] = { symbol = "luaopen_hs_libwebview" },
  ["hs.libwebviewdatastore"] = { symbol = "luaopen_hs_libwebviewdatastore" },
  ["hs.libwebviewtoolbar"] = { symbol = "luaopen_hs_libwebviewtoolbar" },
  ["hs.libwebviewusercontent"] = { symbol = "luaopen_hs_libwebviewusercontent" },
  ["hs.libwifi"] = { symbol = "luaopen_hs_libwifi" },
  ["hs.libwifiwatcher"] = { symbol = "luaopen_hs_libwifiwatcher" },
  ["hs.libwindow"] = { symbol = "luaopen_hs_libwindow" },
}

M.nativeModuleList = {
  { name = "hs.libapplication", symbol = "luaopen_hs_libapplication" },
  { name = "hs.libapplicationwatcher", symbol = "luaopen_hs_libapplicationwatcher" },
  { name = "hs.libaudiodevice", symbol = "luaopen_hs_libaudiodevice" },
  { name = "hs.libaudiodevicewatcher", symbol = "luaopen_hs_libaudiodevicewatcher" },
  { name = "hs.libaxuielement", symbol = "luaopen_hs_libaxuielement" },
  { name = "hs.libbase64", symbol = "luaopen_hs_libbase64" },
  { name = "hs.libbattery", symbol = "luaopen_hs_libbattery" },
  { name = "hs.libbatterywatcher", symbol = "luaopen_hs_libbatterywatcher" },
  { name = "hs.libbonjour", symbol = "luaopen_hs_libbonjour" },
  { name = "hs.libbonjourservice", symbol = "luaopen_hs_libbonjourservice" },
  { name = "hs.libbrightness", symbol = "luaopen_hs_libbrightness" },
  { name = "hs.libcaffeinate", symbol = "luaopen_hs_libcaffeinate" },
  { name = "hs.libcaffeinatewatcher", symbol = "luaopen_hs_libcaffeinatewatcher" },
  { name = "hs.libcamera", symbol = "luaopen_hs_libcamera" },
  { name = "hs.libcanvas", symbol = "luaopen_hs_libcanvas" },
  { name = "hs.libcanvasmatrix", symbol = "luaopen_hs_libcanvasmatrix" },
  { name = "hs.libchooser", symbol = "luaopen_hs_libchooser" },
  { name = "hs.libconsole", symbol = "luaopen_hs_libconsole" },
  { name = "hs.libcrash", symbol = "luaopen_hs_libcrash" },
  { name = "hs.libdialog", symbol = "luaopen_hs_libdialog" },
  { name = "hs.libdistributednotifications", symbol = "luaopen_hs_libdistributednotifications" },
  { name = "hs.libdoc", symbol = "luaopen_hs_libdoc" },
  { name = "hs.libdockicon", symbol = "luaopen_hs_libdockicon" },
  { name = "hs.libdrawing_color", symbol = "luaopen_hs_libdrawing_color" },
  { name = "hs.libeventtap", symbol = "luaopen_hs_libeventtap" },
  { name = "hs.libeventtapevent", symbol = "luaopen_hs_libeventtapevent" },
  { name = "hs.libfs", symbol = "luaopen_hs_libfs" },
  { name = "hs.libfsvolume", symbol = "luaopen_hs_libfsvolume" },
  { name = "hs.libfsxattr", symbol = "luaopen_hs_libfsxattr" },
  { name = "hs.libhash", symbol = "luaopen_hs_libhash" },
  { name = "hs.libhid", symbol = "luaopen_hs_libhid" },
  { name = "hs.libhints", symbol = "luaopen_hs_libhints" },
  { name = "hs.libhost", symbol = "luaopen_hs_libhost" },
  { name = "hs.libhost_locale", symbol = "luaopen_hs_libhost_locale" },
  { name = "hs.libhotkey", symbol = "luaopen_hs_libhotkey" },
  { name = "hs.libhttp", symbol = "luaopen_hs_libhttp" },
  { name = "hs.libhttpserver", symbol = "luaopen_hs_libhttpserver" },
  { name = "hs.libimage", symbol = "luaopen_hs_libimage" },
  { name = "hs.libipc", symbol = "luaopen_hs_libipc" },
  { name = "hs.libjson", symbol = "luaopen_hs_libjson" },
  { name = "hs.libkeycodes", symbol = "luaopen_hs_libkeycodes" },
  { name = "hs.liblocation", symbol = "luaopen_hs_liblocation" },
  { name = "hs.liblsqlite3", symbol = "luaopen_hs_liblsqlite3" },
  { name = "hs.libmarkdown", symbol = "luaopen_hs_libmarkdown" },
  { name = "hs.libmath", symbol = "luaopen_hs_libmath" },
  { name = "hs.libmenubar", symbol = "luaopen_hs_libmenubar" },
  { name = "hs.libmidi", symbol = "luaopen_hs_libmidi" },
  { name = "hs.libmilight", symbol = "luaopen_hs_libmilight" },
  { name = "hs.libmouse", symbol = "luaopen_hs_libmouse" },
  { name = "hs.libnetworkconfiguration", symbol = "luaopen_hs_libnetworkconfiguration" },
  { name = "hs.libnetworkhost", symbol = "luaopen_hs_libnetworkhost" },
  { name = "hs.libnetworkping", symbol = "luaopen_hs_libnetworkping" },
  { name = "hs.libnetworkreachability", symbol = "luaopen_hs_libnetworkreachability" },
  { name = "hs.libnoises", symbol = "luaopen_hs_libnoises" },
  { name = "hs.libnotify", symbol = "luaopen_hs_libnotify" },
  { name = "hs.libosascript", symbol = "luaopen_hs_libosascript" },
  { name = "hs.libpasteboard", symbol = "luaopen_hs_libpasteboard" },
  { name = "hs.libpasteboardwatcher", symbol = "luaopen_hs_libpasteboardwatcher" },
  { name = "hs.libpathwatcher", symbol = "luaopen_hs_libpathwatcher" },
  { name = "hs.libplist", symbol = "luaopen_hs_libplist" },
  { name = "hs.librazer", symbol = "luaopen_hs_librazer" },
  { name = "hs.libscreen", symbol = "luaopen_hs_libscreen" },
  { name = "hs.libscreenwatcher", symbol = "luaopen_hs_libscreenwatcher" },
  { name = "hs.libserial", symbol = "luaopen_hs_libserial" },
  { name = "hs.libsettings", symbol = "luaopen_hs_libsettings" },
  { name = "hs.libsharing", symbol = "luaopen_hs_libsharing" },
  { name = "hs.libshortcuts", symbol = "luaopen_hs_libshortcuts" },
  { name = "hs.libsocket", symbol = "luaopen_hs_libsocket" },
  { name = "hs.libsocketudp", symbol = "luaopen_hs_libsocketudp" },
  { name = "hs.libsound", symbol = "luaopen_hs_libsound" },
  { name = "hs.libspaces", symbol = "luaopen_hs_libspaces" },
  { name = "hs.libspaces_watcher", symbol = "luaopen_hs_libspaces_watcher" },
  { name = "hs.libspeech", symbol = "luaopen_hs_libspeech" },
  { name = "hs.libspeechlistener", symbol = "luaopen_hs_libspeechlistener" },
  { name = "hs.libspotlight", symbol = "luaopen_hs_libspotlight" },
  { name = "hs.libstreamdeck", symbol = "luaopen_hs_libstreamdeck" },
  { name = "hs.libstyledtext", symbol = "luaopen_hs_libstyledtext" },
  { name = "hs.libtask", symbol = "luaopen_hs_libtask" },
  { name = "hs.libtimer", symbol = "luaopen_hs_libtimer" },
  { name = "hs.libuielement", symbol = "luaopen_hs_libuielement" },
  { name = "hs.libuielementwatcher", symbol = "luaopen_hs_libuielementwatcher" },
  { name = "hs.liburlevent", symbol = "luaopen_hs_liburlevent" },
  { name = "hs.libusb", symbol = "luaopen_hs_libusb" },
  { name = "hs.libusbwatcher", symbol = "luaopen_hs_libusbwatcher" },
  { name = "hs.libwebsocket", symbol = "luaopen_hs_libwebsocket" },
  { name = "hs.libwebview", symbol = "luaopen_hs_libwebview" },
  { name = "hs.libwebviewdatastore", symbol = "luaopen_hs_libwebviewdatastore" },
  { name = "hs.libwebviewtoolbar", symbol = "luaopen_hs_libwebviewtoolbar" },
  { name = "hs.libwebviewusercontent", symbol = "luaopen_hs_libwebviewusercontent" },
  { name = "hs.libwifi", symbol = "luaopen_hs_libwifi" },
  { name = "hs.libwifiwatcher", symbol = "luaopen_hs_libwifiwatcher" },
  { name = "hs.libwindow", symbol = "luaopen_hs_libwindow" },
}

M.luaModules = {
  ["hs._boot"] = { source = "extensions/_coresetup/_boot.lua", bundlePath = "hs/_boot.lua" },
  ["hs._coresetup"] = { source = "extensions/_coresetup/_coresetup.lua", bundlePath = "hs/_coresetup.lua" },
  ["hs._loader_metadata"] = { source = "extensions/_coresetup/_loader_metadata.lua", bundlePath = "hs/_loader_metadata.lua" },
  ["hs.alert"] = { source = "extensions/alert/alert.lua", bundlePath = "hs/alert.lua" },
  ["hs.appfinder"] = { source = "extensions/appfinder/appfinder.lua", bundlePath = "hs/appfinder.lua" },
  ["hs.applescript"] = { source = "extensions/applescript/applescript.lua", bundlePath = "hs/applescript.lua" },
  ["hs.application"] = { source = "extensions/application/application.lua", bundlePath = "hs/application.lua" },
  ["hs.audiodevice"] = { source = "extensions/audiodevice/audiodevice.lua", bundlePath = "hs/audiodevice.lua" },
  ["hs.axuielement"] = { source = "extensions/axuielement/axuielement.lua", bundlePath = "hs/axuielement.lua" },
  ["hs.base64"] = { source = "extensions/base64/base64.lua", bundlePath = "hs/base64.lua" },
  ["hs.battery"] = { source = "extensions/battery/battery.lua", bundlePath = "hs/battery.lua" },
  ["hs.bonjour"] = { source = "extensions/bonjour/bonjour.lua", bundlePath = "hs/bonjour.lua" },
  ["hs.brightness"] = { source = "extensions/brightness/brightness.lua", bundlePath = "hs/brightness.lua" },
  ["hs.caffeinate"] = { source = "extensions/caffeinate/caffeinate.lua", bundlePath = "hs/caffeinate.lua" },
  ["hs.camera"] = { source = "extensions/camera/camera.lua", bundlePath = "hs/camera.lua" },
  ["hs.canvas"] = { source = "extensions/canvas/canvas.lua", bundlePath = "hs/canvas.lua" },
  ["hs.canvas_matrix"] = { source = "extensions/canvas/canvas_matrix.lua", bundlePath = "hs/canvas_matrix.lua" },
  ["hs.cgilua_compatibility_functions"] = { source = "extensions/httpserver/cgilua_compatibility_functions.lua", bundlePath = "hs/cgilua_compatibility_functions.lua" },
  ["hs.chooser"] = { source = "extensions/chooser/chooser.lua", bundlePath = "hs/chooser.lua" },
  ["hs.console"] = { source = "extensions/console/console.lua", bundlePath = "hs/console.lua" },
  ["hs.crash"] = { source = "extensions/crash/crash.lua", bundlePath = "hs/crash.lua" },
  ["hs.deezer"] = { source = "extensions/deezer/deezer.lua", bundlePath = "hs/deezer.lua" },
  ["hs.dialog"] = { source = "extensions/dialog/dialog.lua", bundlePath = "hs/dialog.lua" },
  ["hs.distributednotifications"] = { source = "extensions/distributednotifications/distributednotifications.lua", bundlePath = "hs/distributednotifications.lua" },
  ["hs.doc"] = { source = "extensions/doc/doc.lua", bundlePath = "hs/doc.lua" },
  ["hs.doc_builder"] = { source = "extensions/doc/doc_builder.lua", bundlePath = "hs/doc_builder.lua" },
  ["hs.dockicon"] = { source = "extensions/dockicon/dockicon.lua", bundlePath = "hs/dockicon.lua" },
  ["hs.drawing"] = { source = "extensions/drawing/drawing.lua", bundlePath = "hs/drawing.lua" },
  ["hs.drawing_canvasWrapper"] = { source = "extensions/drawing/drawing_canvasWrapper.lua", bundlePath = "hs/drawing_canvasWrapper.lua" },
  ["hs.drawing_color"] = { source = "extensions/drawing/color/drawing_color.lua", bundlePath = "hs/drawing_color.lua" },
  ["hs.eventtap"] = { source = "extensions/eventtap/eventtap.lua", bundlePath = "hs/eventtap.lua" },
  ["hs.expose"] = { source = "extensions/expose/expose.lua", bundlePath = "hs/expose.lua" },
  ["hs.fnutils"] = { source = "extensions/fnutils/fnutils.lua", bundlePath = "hs/fnutils.lua" },
  ["hs.fs"] = { source = "extensions/fs/fs.lua", bundlePath = "hs/fs.lua" },
  ["hs.geometry"] = { source = "extensions/geometry/geometry.lua", bundlePath = "hs/geometry.lua" },
  ["hs.grid"] = { source = "extensions/grid/grid.lua", bundlePath = "hs/grid.lua" },
  ["hs.hash"] = { source = "extensions/hash/hash.lua", bundlePath = "hs/hash.lua" },
  ["hs.hid"] = { source = "extensions/hid/hid.lua", bundlePath = "hs/hid.lua" },
  ["hs.hints"] = { source = "extensions/hints/hints.lua", bundlePath = "hs/hints.lua" },
  ["hs.host"] = { source = "extensions/host/host.lua", bundlePath = "hs/host.lua" },
  ["hs.host_locale"] = { source = "extensions/host/locale/host_locale.lua", bundlePath = "hs/host_locale.lua" },
  ["hs.hotkey"] = { source = "extensions/hotkey/hotkey.lua", bundlePath = "hs/hotkey.lua" },
  ["hs.hsdocs"] = { source = "extensions/doc/hsdocs/init.lua", bundlePath = "hs/hsdocs/init.lua" },
  ["hs.http"] = { source = "extensions/http/http.lua", bundlePath = "hs/http.lua" },
  ["hs.httpserver"] = { source = "extensions/httpserver/httpserver.lua", bundlePath = "hs/httpserver.lua" },
  ["hs.httpserver_hsminweb"] = { source = "extensions/httpserver/httpserver_hsminweb.lua", bundlePath = "hs/httpserver_hsminweb.lua" },
  ["hs.image"] = { source = "extensions/image/image.lua", bundlePath = "hs/image.lua" },
  ["hs.inspect"] = { source = "extensions/inspect/inspect.lua", bundlePath = "hs/inspect.lua" },
  ["hs.ipc"] = { source = "extensions/ipc/ipc.lua", bundlePath = "hs/ipc.lua" },
  ["hs.itunes"] = { source = "extensions/itunes/itunes.lua", bundlePath = "hs/itunes.lua" },
  ["hs.javascript"] = { source = "extensions/javascript/javascript.lua", bundlePath = "hs/javascript.lua" },
  ["hs.json"] = { source = "extensions/json/json.lua", bundlePath = "hs/json.lua" },
  ["hs.keycodes"] = { source = "extensions/keycodes/keycodes.lua", bundlePath = "hs/keycodes.lua" },
  ["hs.layout"] = { source = "extensions/layout/layout.lua", bundlePath = "hs/layout.lua" },
  ["hs.location"] = { source = "extensions/location/location.lua", bundlePath = "hs/location.lua" },
  ["hs.location_geocoder"] = { source = "extensions/location/location_geocoder.lua", bundlePath = "hs/location_geocoder.lua" },
  ["hs.logger"] = { source = "extensions/logger/logger.lua", bundlePath = "hs/logger.lua" },
  ["hs.math"] = { source = "extensions/math/math.lua", bundlePath = "hs/math.lua" },
  ["hs.menubar"] = { source = "extensions/menubar/menubar.lua", bundlePath = "hs/menubar.lua" },
  ["hs.messages"] = { source = "extensions/messages/messages.lua", bundlePath = "hs/messages.lua" },
  ["hs.midi"] = { source = "extensions/midi/midi.lua", bundlePath = "hs/midi.lua" },
  ["hs.milight"] = { source = "extensions/milight/milight.lua", bundlePath = "hs/milight.lua" },
  ["hs.mjomatic"] = { source = "extensions/mjomatic/mjomatic.lua", bundlePath = "hs/mjomatic.lua" },
  ["hs.mouse"] = { source = "extensions/mouse/mouse.lua", bundlePath = "hs/mouse.lua" },
  ["hs.network"] = { source = "extensions/network/network.lua", bundlePath = "hs/network.lua" },
  ["hs.network_configuration"] = { source = "extensions/network/network_configuration.lua", bundlePath = "hs/network_configuration.lua" },
  ["hs.network_host"] = { source = "extensions/network/network_host.lua", bundlePath = "hs/network_host.lua" },
  ["hs.network_ping"] = { source = "extensions/network/ping/network_ping.lua", bundlePath = "hs/network_ping.lua" },
  ["hs.network_reachability"] = { source = "extensions/network/network_reachability.lua", bundlePath = "hs/network_reachability.lua" },
  ["hs.noises"] = { source = "extensions/noises/noises.lua", bundlePath = "hs/noises.lua" },
  ["hs.notify"] = { source = "extensions/notify/notify.lua", bundlePath = "hs/notify.lua" },
  ["hs.osascript"] = { source = "extensions/osascript/osascript.lua", bundlePath = "hs/osascript.lua" },
  ["hs.pasteboard"] = { source = "extensions/pasteboard/pasteboard.lua", bundlePath = "hs/pasteboard.lua" },
  ["hs.pathwatcher"] = { source = "extensions/pathwatcher/pathwatcher.lua", bundlePath = "hs/pathwatcher.lua" },
  ["hs.plist"] = { source = "extensions/plist/plist.lua", bundlePath = "hs/plist.lua" },
  ["hs.razer"] = { source = "extensions/razer/razer.lua", bundlePath = "hs/razer.lua" },
  ["hs.redshift"] = { source = "extensions/redshift/redshift.lua", bundlePath = "hs/redshift.lua" },
  ["hs.screen"] = { source = "extensions/screen/screen.lua", bundlePath = "hs/screen.lua" },
  ["hs.serial"] = { source = "extensions/serial/serial.lua", bundlePath = "hs/serial.lua" },
  ["hs.settings"] = { source = "extensions/settings/settings.lua", bundlePath = "hs/settings.lua" },
  ["hs.sharing"] = { source = "extensions/sharing/sharing.lua", bundlePath = "hs/sharing.lua" },
  ["hs.shortcuts"] = { source = "extensions/shortcuts/shortcuts.lua", bundlePath = "hs/shortcuts.lua" },
  ["hs.socket"] = { source = "extensions/socket/socket.lua", bundlePath = "hs/socket.lua" },
  ["hs.sound"] = { source = "extensions/sound/sound.lua", bundlePath = "hs/sound.lua" },
  ["hs.spaces"] = { source = "extensions/spaces/spaces.lua", bundlePath = "hs/spaces.lua" },
  ["hs.speech"] = { source = "extensions/speech/speech.lua", bundlePath = "hs/speech.lua" },
  ["hs.spoons"] = { source = "extensions/spoons/spoons.lua", bundlePath = "hs/spoons.lua" },
  ["hs.spotify"] = { source = "extensions/spotify/spotify.lua", bundlePath = "hs/spotify.lua" },
  ["hs.spotlight"] = { source = "extensions/spotlight/spotlight.lua", bundlePath = "hs/spotlight.lua" },
  ["hs.sqlite3"] = { source = "extensions/sqlite3/sqlite3.lua", bundlePath = "hs/sqlite3.lua" },
  ["hs.streamdeck"] = { source = "extensions/streamdeck/streamdeck.lua", bundlePath = "hs/streamdeck.lua" },
  ["hs.styledtext"] = { source = "extensions/styledtext/styledtext.lua", bundlePath = "hs/styledtext.lua" },
  ["hs.tabs"] = { source = "extensions/tabs/tabs.lua", bundlePath = "hs/tabs.lua" },
  ["hs.tangent"] = { source = "extensions/tangent/tangent.lua", bundlePath = "hs/tangent.lua" },
  ["hs.task"] = { source = "extensions/task/task.lua", bundlePath = "hs/task.lua" },
  ["hs.timer"] = { source = "extensions/timer/timer.lua", bundlePath = "hs/timer.lua" },
  ["hs.uielement"] = { source = "extensions/uielement/uielement.lua", bundlePath = "hs/uielement.lua" },
  ["hs.urlevent"] = { source = "extensions/urlevent/urlevent.lua", bundlePath = "hs/urlevent.lua" },
  ["hs.usb"] = { source = "extensions/usb/usb.lua", bundlePath = "hs/usb.lua" },
  ["hs.utf8"] = { source = "extensions/utf8/utf8.lua", bundlePath = "hs/utf8.lua" },
  ["hs.vox"] = { source = "extensions/vox/vox.lua", bundlePath = "hs/vox.lua" },
  ["hs.watchable"] = { source = "extensions/watchable/watchable.lua", bundlePath = "hs/watchable.lua" },
  ["hs.websocket"] = { source = "extensions/websocket/websocket.lua", bundlePath = "hs/websocket.lua" },
  ["hs.webview"] = { source = "extensions/webview/webview.lua", bundlePath = "hs/webview.lua" },
  ["hs.webview_toolbar"] = { source = "extensions/webview/webview_toolbar.lua", bundlePath = "hs/webview_toolbar.lua" },
  ["hs.wifi"] = { source = "extensions/wifi/wifi.lua", bundlePath = "hs/wifi.lua" },
  ["hs.window"] = { source = "extensions/window/window.lua", bundlePath = "hs/window.lua" },
  ["hs.window_filter"] = { source = "extensions/window/window_filter.lua", bundlePath = "hs/window_filter.lua" },
  ["hs.window_highlight"] = { source = "extensions/window/window_highlight.lua", bundlePath = "hs/window_highlight.lua" },
  ["hs.window_layout"] = { source = "extensions/window/window_layout.lua", bundlePath = "hs/window_layout.lua" },
  ["hs.window_switcher"] = { source = "extensions/window/window_switcher.lua", bundlePath = "hs/window_switcher.lua" },
  ["hs.window_tiling"] = { source = "extensions/window/window_tiling.lua", bundlePath = "hs/window_tiling.lua" },
}

M.luaModuleList = {
  { name = "hs._boot", source = "extensions/_coresetup/_boot.lua", bundlePath = "hs/_boot.lua" },
  { name = "hs._coresetup", source = "extensions/_coresetup/_coresetup.lua", bundlePath = "hs/_coresetup.lua" },
  { name = "hs._loader_metadata", source = "extensions/_coresetup/_loader_metadata.lua", bundlePath = "hs/_loader_metadata.lua" },
  { name = "hs.alert", source = "extensions/alert/alert.lua", bundlePath = "hs/alert.lua" },
  { name = "hs.appfinder", source = "extensions/appfinder/appfinder.lua", bundlePath = "hs/appfinder.lua" },
  { name = "hs.applescript", source = "extensions/applescript/applescript.lua", bundlePath = "hs/applescript.lua" },
  { name = "hs.application", source = "extensions/application/application.lua", bundlePath = "hs/application.lua" },
  { name = "hs.audiodevice", source = "extensions/audiodevice/audiodevice.lua", bundlePath = "hs/audiodevice.lua" },
  { name = "hs.axuielement", source = "extensions/axuielement/axuielement.lua", bundlePath = "hs/axuielement.lua" },
  { name = "hs.base64", source = "extensions/base64/base64.lua", bundlePath = "hs/base64.lua" },
  { name = "hs.battery", source = "extensions/battery/battery.lua", bundlePath = "hs/battery.lua" },
  { name = "hs.bonjour", source = "extensions/bonjour/bonjour.lua", bundlePath = "hs/bonjour.lua" },
  { name = "hs.brightness", source = "extensions/brightness/brightness.lua", bundlePath = "hs/brightness.lua" },
  { name = "hs.caffeinate", source = "extensions/caffeinate/caffeinate.lua", bundlePath = "hs/caffeinate.lua" },
  { name = "hs.camera", source = "extensions/camera/camera.lua", bundlePath = "hs/camera.lua" },
  { name = "hs.canvas", source = "extensions/canvas/canvas.lua", bundlePath = "hs/canvas.lua" },
  { name = "hs.canvas_matrix", source = "extensions/canvas/canvas_matrix.lua", bundlePath = "hs/canvas_matrix.lua" },
  { name = "hs.cgilua_compatibility_functions", source = "extensions/httpserver/cgilua_compatibility_functions.lua", bundlePath = "hs/cgilua_compatibility_functions.lua" },
  { name = "hs.chooser", source = "extensions/chooser/chooser.lua", bundlePath = "hs/chooser.lua" },
  { name = "hs.console", source = "extensions/console/console.lua", bundlePath = "hs/console.lua" },
  { name = "hs.crash", source = "extensions/crash/crash.lua", bundlePath = "hs/crash.lua" },
  { name = "hs.deezer", source = "extensions/deezer/deezer.lua", bundlePath = "hs/deezer.lua" },
  { name = "hs.dialog", source = "extensions/dialog/dialog.lua", bundlePath = "hs/dialog.lua" },
  { name = "hs.distributednotifications", source = "extensions/distributednotifications/distributednotifications.lua", bundlePath = "hs/distributednotifications.lua" },
  { name = "hs.doc", source = "extensions/doc/doc.lua", bundlePath = "hs/doc.lua" },
  { name = "hs.doc_builder", source = "extensions/doc/doc_builder.lua", bundlePath = "hs/doc_builder.lua" },
  { name = "hs.dockicon", source = "extensions/dockicon/dockicon.lua", bundlePath = "hs/dockicon.lua" },
  { name = "hs.drawing", source = "extensions/drawing/drawing.lua", bundlePath = "hs/drawing.lua" },
  { name = "hs.drawing_canvasWrapper", source = "extensions/drawing/drawing_canvasWrapper.lua", bundlePath = "hs/drawing_canvasWrapper.lua" },
  { name = "hs.drawing_color", source = "extensions/drawing/color/drawing_color.lua", bundlePath = "hs/drawing_color.lua" },
  { name = "hs.eventtap", source = "extensions/eventtap/eventtap.lua", bundlePath = "hs/eventtap.lua" },
  { name = "hs.expose", source = "extensions/expose/expose.lua", bundlePath = "hs/expose.lua" },
  { name = "hs.fnutils", source = "extensions/fnutils/fnutils.lua", bundlePath = "hs/fnutils.lua" },
  { name = "hs.fs", source = "extensions/fs/fs.lua", bundlePath = "hs/fs.lua" },
  { name = "hs.geometry", source = "extensions/geometry/geometry.lua", bundlePath = "hs/geometry.lua" },
  { name = "hs.grid", source = "extensions/grid/grid.lua", bundlePath = "hs/grid.lua" },
  { name = "hs.hash", source = "extensions/hash/hash.lua", bundlePath = "hs/hash.lua" },
  { name = "hs.hid", source = "extensions/hid/hid.lua", bundlePath = "hs/hid.lua" },
  { name = "hs.hints", source = "extensions/hints/hints.lua", bundlePath = "hs/hints.lua" },
  { name = "hs.host", source = "extensions/host/host.lua", bundlePath = "hs/host.lua" },
  { name = "hs.host_locale", source = "extensions/host/locale/host_locale.lua", bundlePath = "hs/host_locale.lua" },
  { name = "hs.hotkey", source = "extensions/hotkey/hotkey.lua", bundlePath = "hs/hotkey.lua" },
  { name = "hs.hsdocs", source = "extensions/doc/hsdocs/init.lua", bundlePath = "hs/hsdocs/init.lua" },
  { name = "hs.http", source = "extensions/http/http.lua", bundlePath = "hs/http.lua" },
  { name = "hs.httpserver", source = "extensions/httpserver/httpserver.lua", bundlePath = "hs/httpserver.lua" },
  { name = "hs.httpserver_hsminweb", source = "extensions/httpserver/httpserver_hsminweb.lua", bundlePath = "hs/httpserver_hsminweb.lua" },
  { name = "hs.image", source = "extensions/image/image.lua", bundlePath = "hs/image.lua" },
  { name = "hs.inspect", source = "extensions/inspect/inspect.lua", bundlePath = "hs/inspect.lua" },
  { name = "hs.ipc", source = "extensions/ipc/ipc.lua", bundlePath = "hs/ipc.lua" },
  { name = "hs.itunes", source = "extensions/itunes/itunes.lua", bundlePath = "hs/itunes.lua" },
  { name = "hs.javascript", source = "extensions/javascript/javascript.lua", bundlePath = "hs/javascript.lua" },
  { name = "hs.json", source = "extensions/json/json.lua", bundlePath = "hs/json.lua" },
  { name = "hs.keycodes", source = "extensions/keycodes/keycodes.lua", bundlePath = "hs/keycodes.lua" },
  { name = "hs.layout", source = "extensions/layout/layout.lua", bundlePath = "hs/layout.lua" },
  { name = "hs.location", source = "extensions/location/location.lua", bundlePath = "hs/location.lua" },
  { name = "hs.location_geocoder", source = "extensions/location/location_geocoder.lua", bundlePath = "hs/location_geocoder.lua" },
  { name = "hs.logger", source = "extensions/logger/logger.lua", bundlePath = "hs/logger.lua" },
  { name = "hs.math", source = "extensions/math/math.lua", bundlePath = "hs/math.lua" },
  { name = "hs.menubar", source = "extensions/menubar/menubar.lua", bundlePath = "hs/menubar.lua" },
  { name = "hs.messages", source = "extensions/messages/messages.lua", bundlePath = "hs/messages.lua" },
  { name = "hs.midi", source = "extensions/midi/midi.lua", bundlePath = "hs/midi.lua" },
  { name = "hs.milight", source = "extensions/milight/milight.lua", bundlePath = "hs/milight.lua" },
  { name = "hs.mjomatic", source = "extensions/mjomatic/mjomatic.lua", bundlePath = "hs/mjomatic.lua" },
  { name = "hs.mouse", source = "extensions/mouse/mouse.lua", bundlePath = "hs/mouse.lua" },
  { name = "hs.network", source = "extensions/network/network.lua", bundlePath = "hs/network.lua" },
  { name = "hs.network_configuration", source = "extensions/network/network_configuration.lua", bundlePath = "hs/network_configuration.lua" },
  { name = "hs.network_host", source = "extensions/network/network_host.lua", bundlePath = "hs/network_host.lua" },
  { name = "hs.network_ping", source = "extensions/network/ping/network_ping.lua", bundlePath = "hs/network_ping.lua" },
  { name = "hs.network_reachability", source = "extensions/network/network_reachability.lua", bundlePath = "hs/network_reachability.lua" },
  { name = "hs.noises", source = "extensions/noises/noises.lua", bundlePath = "hs/noises.lua" },
  { name = "hs.notify", source = "extensions/notify/notify.lua", bundlePath = "hs/notify.lua" },
  { name = "hs.osascript", source = "extensions/osascript/osascript.lua", bundlePath = "hs/osascript.lua" },
  { name = "hs.pasteboard", source = "extensions/pasteboard/pasteboard.lua", bundlePath = "hs/pasteboard.lua" },
  { name = "hs.pathwatcher", source = "extensions/pathwatcher/pathwatcher.lua", bundlePath = "hs/pathwatcher.lua" },
  { name = "hs.plist", source = "extensions/plist/plist.lua", bundlePath = "hs/plist.lua" },
  { name = "hs.razer", source = "extensions/razer/razer.lua", bundlePath = "hs/razer.lua" },
  { name = "hs.redshift", source = "extensions/redshift/redshift.lua", bundlePath = "hs/redshift.lua" },
  { name = "hs.screen", source = "extensions/screen/screen.lua", bundlePath = "hs/screen.lua" },
  { name = "hs.serial", source = "extensions/serial/serial.lua", bundlePath = "hs/serial.lua" },
  { name = "hs.settings", source = "extensions/settings/settings.lua", bundlePath = "hs/settings.lua" },
  { name = "hs.sharing", source = "extensions/sharing/sharing.lua", bundlePath = "hs/sharing.lua" },
  { name = "hs.shortcuts", source = "extensions/shortcuts/shortcuts.lua", bundlePath = "hs/shortcuts.lua" },
  { name = "hs.socket", source = "extensions/socket/socket.lua", bundlePath = "hs/socket.lua" },
  { name = "hs.sound", source = "extensions/sound/sound.lua", bundlePath = "hs/sound.lua" },
  { name = "hs.spaces", source = "extensions/spaces/spaces.lua", bundlePath = "hs/spaces.lua" },
  { name = "hs.speech", source = "extensions/speech/speech.lua", bundlePath = "hs/speech.lua" },
  { name = "hs.spoons", source = "extensions/spoons/spoons.lua", bundlePath = "hs/spoons.lua" },
  { name = "hs.spotify", source = "extensions/spotify/spotify.lua", bundlePath = "hs/spotify.lua" },
  { name = "hs.spotlight", source = "extensions/spotlight/spotlight.lua", bundlePath = "hs/spotlight.lua" },
  { name = "hs.sqlite3", source = "extensions/sqlite3/sqlite3.lua", bundlePath = "hs/sqlite3.lua" },
  { name = "hs.streamdeck", source = "extensions/streamdeck/streamdeck.lua", bundlePath = "hs/streamdeck.lua" },
  { name = "hs.styledtext", source = "extensions/styledtext/styledtext.lua", bundlePath = "hs/styledtext.lua" },
  { name = "hs.tabs", source = "extensions/tabs/tabs.lua", bundlePath = "hs/tabs.lua" },
  { name = "hs.tangent", source = "extensions/tangent/tangent.lua", bundlePath = "hs/tangent.lua" },
  { name = "hs.task", source = "extensions/task/task.lua", bundlePath = "hs/task.lua" },
  { name = "hs.timer", source = "extensions/timer/timer.lua", bundlePath = "hs/timer.lua" },
  { name = "hs.uielement", source = "extensions/uielement/uielement.lua", bundlePath = "hs/uielement.lua" },
  { name = "hs.urlevent", source = "extensions/urlevent/urlevent.lua", bundlePath = "hs/urlevent.lua" },
  { name = "hs.usb", source = "extensions/usb/usb.lua", bundlePath = "hs/usb.lua" },
  { name = "hs.utf8", source = "extensions/utf8/utf8.lua", bundlePath = "hs/utf8.lua" },
  { name = "hs.vox", source = "extensions/vox/vox.lua", bundlePath = "hs/vox.lua" },
  { name = "hs.watchable", source = "extensions/watchable/watchable.lua", bundlePath = "hs/watchable.lua" },
  { name = "hs.websocket", source = "extensions/websocket/websocket.lua", bundlePath = "hs/websocket.lua" },
  { name = "hs.webview", source = "extensions/webview/webview.lua", bundlePath = "hs/webview.lua" },
  { name = "hs.webview_toolbar", source = "extensions/webview/webview_toolbar.lua", bundlePath = "hs/webview_toolbar.lua" },
  { name = "hs.wifi", source = "extensions/wifi/wifi.lua", bundlePath = "hs/wifi.lua" },
  { name = "hs.window", source = "extensions/window/window.lua", bundlePath = "hs/window.lua" },
  { name = "hs.window_filter", source = "extensions/window/window_filter.lua", bundlePath = "hs/window_filter.lua" },
  { name = "hs.window_highlight", source = "extensions/window/window_highlight.lua", bundlePath = "hs/window_highlight.lua" },
  { name = "hs.window_layout", source = "extensions/window/window_layout.lua", bundlePath = "hs/window_layout.lua" },
  { name = "hs.window_switcher", source = "extensions/window/window_switcher.lua", bundlePath = "hs/window_switcher.lua" },
  { name = "hs.window_tiling", source = "extensions/window/window_tiling.lua", bundlePath = "hs/window_tiling.lua" },
}

M.copyMap = {
  { module = "hs._boot", source = "extensions/_coresetup/_boot.lua", bundlePath = "hs/_boot.lua" },
  { module = "hs._coresetup", source = "extensions/_coresetup/_coresetup.lua", bundlePath = "hs/_coresetup.lua" },
  { module = "hs._loader_metadata", source = "extensions/_coresetup/_loader_metadata.lua", bundlePath = "hs/_loader_metadata.lua" },
  { module = "hs.alert", source = "extensions/alert/alert.lua", bundlePath = "hs/alert.lua" },
  { module = "hs.appfinder", source = "extensions/appfinder/appfinder.lua", bundlePath = "hs/appfinder.lua" },
  { module = "hs.applescript", source = "extensions/applescript/applescript.lua", bundlePath = "hs/applescript.lua" },
  { module = "hs.application", source = "extensions/application/application.lua", bundlePath = "hs/application.lua" },
  { module = "hs.audiodevice", source = "extensions/audiodevice/audiodevice.lua", bundlePath = "hs/audiodevice.lua" },
  { module = "hs.axuielement", source = "extensions/axuielement/axuielement.lua", bundlePath = "hs/axuielement.lua" },
  { module = "hs.base64", source = "extensions/base64/base64.lua", bundlePath = "hs/base64.lua" },
  { module = "hs.battery", source = "extensions/battery/battery.lua", bundlePath = "hs/battery.lua" },
  { module = "hs.bonjour", source = "extensions/bonjour/bonjour.lua", bundlePath = "hs/bonjour.lua" },
  { module = "hs.brightness", source = "extensions/brightness/brightness.lua", bundlePath = "hs/brightness.lua" },
  { module = "hs.caffeinate", source = "extensions/caffeinate/caffeinate.lua", bundlePath = "hs/caffeinate.lua" },
  { module = "hs.camera", source = "extensions/camera/camera.lua", bundlePath = "hs/camera.lua" },
  { module = "hs.canvas", source = "extensions/canvas/canvas.lua", bundlePath = "hs/canvas.lua" },
  { module = "hs.canvas_matrix", source = "extensions/canvas/canvas_matrix.lua", bundlePath = "hs/canvas_matrix.lua" },
  { module = "hs.cgilua_compatibility_functions", source = "extensions/httpserver/cgilua_compatibility_functions.lua", bundlePath = "hs/cgilua_compatibility_functions.lua" },
  { module = "hs.chooser", source = "extensions/chooser/chooser.lua", bundlePath = "hs/chooser.lua" },
  { module = "hs.console", source = "extensions/console/console.lua", bundlePath = "hs/console.lua" },
  { module = "hs.crash", source = "extensions/crash/crash.lua", bundlePath = "hs/crash.lua" },
  { module = "hs.deezer", source = "extensions/deezer/deezer.lua", bundlePath = "hs/deezer.lua" },
  { module = "hs.dialog", source = "extensions/dialog/dialog.lua", bundlePath = "hs/dialog.lua" },
  { module = "hs.distributednotifications", source = "extensions/distributednotifications/distributednotifications.lua", bundlePath = "hs/distributednotifications.lua" },
  { module = "hs.doc", source = "extensions/doc/doc.lua", bundlePath = "hs/doc.lua" },
  { module = "hs.doc_builder", source = "extensions/doc/doc_builder.lua", bundlePath = "hs/doc_builder.lua" },
  { module = "hs.dockicon", source = "extensions/dockicon/dockicon.lua", bundlePath = "hs/dockicon.lua" },
  { module = "hs.drawing", source = "extensions/drawing/drawing.lua", bundlePath = "hs/drawing.lua" },
  { module = "hs.drawing_canvasWrapper", source = "extensions/drawing/drawing_canvasWrapper.lua", bundlePath = "hs/drawing_canvasWrapper.lua" },
  { module = "hs.drawing_color", source = "extensions/drawing/color/drawing_color.lua", bundlePath = "hs/drawing_color.lua" },
  { module = "hs.eventtap", source = "extensions/eventtap/eventtap.lua", bundlePath = "hs/eventtap.lua" },
  { module = "hs.expose", source = "extensions/expose/expose.lua", bundlePath = "hs/expose.lua" },
  { module = "hs.fnutils", source = "extensions/fnutils/fnutils.lua", bundlePath = "hs/fnutils.lua" },
  { module = "hs.fs", source = "extensions/fs/fs.lua", bundlePath = "hs/fs.lua" },
  { module = "hs.geometry", source = "extensions/geometry/geometry.lua", bundlePath = "hs/geometry.lua" },
  { module = "hs.grid", source = "extensions/grid/grid.lua", bundlePath = "hs/grid.lua" },
  { module = "hs.hash", source = "extensions/hash/hash.lua", bundlePath = "hs/hash.lua" },
  { module = "hs.hid", source = "extensions/hid/hid.lua", bundlePath = "hs/hid.lua" },
  { module = "hs.hints", source = "extensions/hints/hints.lua", bundlePath = "hs/hints.lua" },
  { module = "hs.host", source = "extensions/host/host.lua", bundlePath = "hs/host.lua" },
  { module = "hs.host_locale", source = "extensions/host/locale/host_locale.lua", bundlePath = "hs/host_locale.lua" },
  { module = "hs.hotkey", source = "extensions/hotkey/hotkey.lua", bundlePath = "hs/hotkey.lua" },
  { module = "hs.hsdocs", source = "extensions/doc/hsdocs/init.lua", bundlePath = "hs/hsdocs/init.lua" },
  { module = "hs.http", source = "extensions/http/http.lua", bundlePath = "hs/http.lua" },
  { module = "hs.httpserver", source = "extensions/httpserver/httpserver.lua", bundlePath = "hs/httpserver.lua" },
  { module = "hs.httpserver_hsminweb", source = "extensions/httpserver/httpserver_hsminweb.lua", bundlePath = "hs/httpserver_hsminweb.lua" },
  { module = "hs.image", source = "extensions/image/image.lua", bundlePath = "hs/image.lua" },
  { module = "hs.inspect", source = "extensions/inspect/inspect.lua", bundlePath = "hs/inspect.lua" },
  { module = "hs.ipc", source = "extensions/ipc/ipc.lua", bundlePath = "hs/ipc.lua" },
  { module = "hs.itunes", source = "extensions/itunes/itunes.lua", bundlePath = "hs/itunes.lua" },
  { module = "hs.javascript", source = "extensions/javascript/javascript.lua", bundlePath = "hs/javascript.lua" },
  { module = "hs.json", source = "extensions/json/json.lua", bundlePath = "hs/json.lua" },
  { module = "hs.keycodes", source = "extensions/keycodes/keycodes.lua", bundlePath = "hs/keycodes.lua" },
  { module = "hs.layout", source = "extensions/layout/layout.lua", bundlePath = "hs/layout.lua" },
  { module = "hs.location", source = "extensions/location/location.lua", bundlePath = "hs/location.lua" },
  { module = "hs.location_geocoder", source = "extensions/location/location_geocoder.lua", bundlePath = "hs/location_geocoder.lua" },
  { module = "hs.logger", source = "extensions/logger/logger.lua", bundlePath = "hs/logger.lua" },
  { module = "hs.math", source = "extensions/math/math.lua", bundlePath = "hs/math.lua" },
  { module = "hs.menubar", source = "extensions/menubar/menubar.lua", bundlePath = "hs/menubar.lua" },
  { module = "hs.messages", source = "extensions/messages/messages.lua", bundlePath = "hs/messages.lua" },
  { module = "hs.midi", source = "extensions/midi/midi.lua", bundlePath = "hs/midi.lua" },
  { module = "hs.milight", source = "extensions/milight/milight.lua", bundlePath = "hs/milight.lua" },
  { module = "hs.mjomatic", source = "extensions/mjomatic/mjomatic.lua", bundlePath = "hs/mjomatic.lua" },
  { module = "hs.mouse", source = "extensions/mouse/mouse.lua", bundlePath = "hs/mouse.lua" },
  { module = "hs.network", source = "extensions/network/network.lua", bundlePath = "hs/network.lua" },
  { module = "hs.network_configuration", source = "extensions/network/network_configuration.lua", bundlePath = "hs/network_configuration.lua" },
  { module = "hs.network_host", source = "extensions/network/network_host.lua", bundlePath = "hs/network_host.lua" },
  { module = "hs.network_ping", source = "extensions/network/ping/network_ping.lua", bundlePath = "hs/network_ping.lua" },
  { module = "hs.network_reachability", source = "extensions/network/network_reachability.lua", bundlePath = "hs/network_reachability.lua" },
  { module = "hs.noises", source = "extensions/noises/noises.lua", bundlePath = "hs/noises.lua" },
  { module = "hs.notify", source = "extensions/notify/notify.lua", bundlePath = "hs/notify.lua" },
  { module = "hs.osascript", source = "extensions/osascript/osascript.lua", bundlePath = "hs/osascript.lua" },
  { module = "hs.pasteboard", source = "extensions/pasteboard/pasteboard.lua", bundlePath = "hs/pasteboard.lua" },
  { module = "hs.pathwatcher", source = "extensions/pathwatcher/pathwatcher.lua", bundlePath = "hs/pathwatcher.lua" },
  { module = "hs.plist", source = "extensions/plist/plist.lua", bundlePath = "hs/plist.lua" },
  { module = "hs.razer", source = "extensions/razer/razer.lua", bundlePath = "hs/razer.lua" },
  { module = "hs.redshift", source = "extensions/redshift/redshift.lua", bundlePath = "hs/redshift.lua" },
  { module = "hs.screen", source = "extensions/screen/screen.lua", bundlePath = "hs/screen.lua" },
  { module = "hs.serial", source = "extensions/serial/serial.lua", bundlePath = "hs/serial.lua" },
  { module = "hs.settings", source = "extensions/settings/settings.lua", bundlePath = "hs/settings.lua" },
  { module = "hs.sharing", source = "extensions/sharing/sharing.lua", bundlePath = "hs/sharing.lua" },
  { module = "hs.shortcuts", source = "extensions/shortcuts/shortcuts.lua", bundlePath = "hs/shortcuts.lua" },
  { module = "hs.socket", source = "extensions/socket/socket.lua", bundlePath = "hs/socket.lua" },
  { module = "hs.sound", source = "extensions/sound/sound.lua", bundlePath = "hs/sound.lua" },
  { module = "hs.spaces", source = "extensions/spaces/spaces.lua", bundlePath = "hs/spaces.lua" },
  { module = "hs.speech", source = "extensions/speech/speech.lua", bundlePath = "hs/speech.lua" },
  { module = "hs.spoons", source = "extensions/spoons/spoons.lua", bundlePath = "hs/spoons.lua" },
  { module = "hs.spotify", source = "extensions/spotify/spotify.lua", bundlePath = "hs/spotify.lua" },
  { module = "hs.spotlight", source = "extensions/spotlight/spotlight.lua", bundlePath = "hs/spotlight.lua" },
  { module = "hs.sqlite3", source = "extensions/sqlite3/sqlite3.lua", bundlePath = "hs/sqlite3.lua" },
  { module = "hs.streamdeck", source = "extensions/streamdeck/streamdeck.lua", bundlePath = "hs/streamdeck.lua" },
  { module = "hs.styledtext", source = "extensions/styledtext/styledtext.lua", bundlePath = "hs/styledtext.lua" },
  { module = "hs.tabs", source = "extensions/tabs/tabs.lua", bundlePath = "hs/tabs.lua" },
  { module = "hs.tangent", source = "extensions/tangent/tangent.lua", bundlePath = "hs/tangent.lua" },
  { module = "hs.task", source = "extensions/task/task.lua", bundlePath = "hs/task.lua" },
  { module = "hs.timer", source = "extensions/timer/timer.lua", bundlePath = "hs/timer.lua" },
  { module = "hs.uielement", source = "extensions/uielement/uielement.lua", bundlePath = "hs/uielement.lua" },
  { module = "hs.urlevent", source = "extensions/urlevent/urlevent.lua", bundlePath = "hs/urlevent.lua" },
  { module = "hs.usb", source = "extensions/usb/usb.lua", bundlePath = "hs/usb.lua" },
  { module = "hs.utf8", source = "extensions/utf8/utf8.lua", bundlePath = "hs/utf8.lua" },
  { module = "hs.vox", source = "extensions/vox/vox.lua", bundlePath = "hs/vox.lua" },
  { module = "hs.watchable", source = "extensions/watchable/watchable.lua", bundlePath = "hs/watchable.lua" },
  { module = "hs.websocket", source = "extensions/websocket/websocket.lua", bundlePath = "hs/websocket.lua" },
  { module = "hs.webview", source = "extensions/webview/webview.lua", bundlePath = "hs/webview.lua" },
  { module = "hs.webview_toolbar", source = "extensions/webview/webview_toolbar.lua", bundlePath = "hs/webview_toolbar.lua" },
  { module = "hs.wifi", source = "extensions/wifi/wifi.lua", bundlePath = "hs/wifi.lua" },
  { module = "hs.window", source = "extensions/window/window.lua", bundlePath = "hs/window.lua" },
  { module = "hs.window_filter", source = "extensions/window/window_filter.lua", bundlePath = "hs/window_filter.lua" },
  { module = "hs.window_highlight", source = "extensions/window/window_highlight.lua", bundlePath = "hs/window_highlight.lua" },
  { module = "hs.window_layout", source = "extensions/window/window_layout.lua", bundlePath = "hs/window_layout.lua" },
  { module = "hs.window_switcher", source = "extensions/window/window_switcher.lua", bundlePath = "hs/window_switcher.lua" },
  { module = "hs.window_tiling", source = "extensions/window/window_tiling.lua", bundlePath = "hs/window_tiling.lua" },
}

M.preloadAliases = {
  { "hs.application.watcher", "hs.libapplicationwatcher" },
  { "hs.audiodevice.watcher", "hs.libaudiodevicewatcher" },
  { "hs.battery.watcher", "hs.libbatterywatcher" },
  { "hs.bonjour.service", "hs.libbonjourservice" },
  { "hs.caffeinate.watcher", "hs.libcaffeinatewatcher" },
  { "hs.canvas.matrix", "hs.canvas_matrix" },
  { "hs.doc.builder", "hs.doc_builder" },
  { "hs.doc.hsdocs", "hs.hsdocs" },
  { "hs.doc.markdown", "hs.libmarkdown" },
  { "hs.drawing.color", "hs.drawing_color" },
  { "hs.fs.volume", "hs.libfsvolume" },
  { "hs.fs.xattr", "hs.libfsxattr" },
  { "hs.host.locale", "hs.host_locale" },
  { "hs.httpserver.hsminweb", "hs.httpserver_hsminweb" },
  { "hs.location.geocoder", "hs.location_geocoder" },
  { "hs.network.configuration", "hs.network_configuration" },
  { "hs.network.host", "hs.network_host" },
  { "hs.network.ping", "hs.network_ping" },
  { "hs.pasteboard.watcher", "hs.libpasteboardwatcher" },
  { "hs.screen.watcher", "hs.libscreenwatcher" },
  { "hs.socket.udp", "hs.libsocketudp" },
  { "hs.spaces.watcher", "hs.libspaces_watcher" },
  { "hs.uielement.watcher", "hs.libuielementwatcher" },
  { "hs.usb.watcher", "hs.libusbwatcher" },
  { "hs.webview.datastore", "hs.libwebviewdatastore" },
  { "hs.webview.toolbar", "hs.webview_toolbar" },
  { "hs.webview.usercontent", "hs.libwebviewusercontent" },
  { "hs.wifi.watcher", "hs.libwifiwatcher" },
  { "hs.window.filter", "hs.window_filter" },
  { "hs.window.highlight", "hs.window_highlight" },
  { "hs.window.layout", "hs.window_layout" },
  { "hs.window.switcher", "hs.window_switcher" },
  { "hs.window.tiling", "hs.window_tiling" },
}

M.aliasTargets = {
  ["hs.application.watcher"] = "hs.libapplicationwatcher",
  ["hs.audiodevice.watcher"] = "hs.libaudiodevicewatcher",
  ["hs.battery.watcher"] = "hs.libbatterywatcher",
  ["hs.bonjour.service"] = "hs.libbonjourservice",
  ["hs.caffeinate.watcher"] = "hs.libcaffeinatewatcher",
  ["hs.canvas.matrix"] = "hs.canvas_matrix",
  ["hs.doc.builder"] = "hs.doc_builder",
  ["hs.doc.hsdocs"] = "hs.hsdocs",
  ["hs.doc.markdown"] = "hs.libmarkdown",
  ["hs.drawing.color"] = "hs.drawing_color",
  ["hs.fs.volume"] = "hs.libfsvolume",
  ["hs.fs.xattr"] = "hs.libfsxattr",
  ["hs.host.locale"] = "hs.host_locale",
  ["hs.httpserver.hsminweb"] = "hs.httpserver_hsminweb",
  ["hs.location.geocoder"] = "hs.location_geocoder",
  ["hs.network.configuration"] = "hs.network_configuration",
  ["hs.network.host"] = "hs.network_host",
  ["hs.network.ping"] = "hs.network_ping",
  ["hs.pasteboard.watcher"] = "hs.libpasteboardwatcher",
  ["hs.screen.watcher"] = "hs.libscreenwatcher",
  ["hs.socket.udp"] = "hs.libsocketudp",
  ["hs.spaces.watcher"] = "hs.libspaces_watcher",
  ["hs.uielement.watcher"] = "hs.libuielementwatcher",
  ["hs.usb.watcher"] = "hs.libusbwatcher",
  ["hs.webview.datastore"] = "hs.libwebviewdatastore",
  ["hs.webview.toolbar"] = "hs.webview_toolbar",
  ["hs.webview.usercontent"] = "hs.libwebviewusercontent",
  ["hs.wifi.watcher"] = "hs.libwifiwatcher",
  ["hs.window.filter"] = "hs.window_filter",
  ["hs.window.highlight"] = "hs.window_highlight",
  ["hs.window.layout"] = "hs.window_layout",
  ["hs.window.switcher"] = "hs.window_switcher",
  ["hs.window.tiling"] = "hs.window_tiling",
}

M.lazyExtensions = {
  ["alert"] = true,
  ["appfinder"] = true,
  ["applescript"] = true,
  ["application"] = true,
  ["audiodevice"] = true,
  ["axuielement"] = true,
  ["base64"] = true,
  ["battery"] = true,
  ["bonjour"] = true,
  ["brightness"] = true,
  ["caffeinate"] = true,
  ["camera"] = true,
  ["canvas"] = true,
  ["chooser"] = true,
  ["console"] = true,
  ["crash"] = true,
  ["deezer"] = true,
  ["dialog"] = true,
  ["distributednotifications"] = true,
  ["doc"] = true,
  ["dockicon"] = true,
  ["drawing"] = true,
  ["eventtap"] = true,
  ["expose"] = true,
  ["fnutils"] = true,
  ["fs"] = true,
  ["geometry"] = true,
  ["grid"] = true,
  ["hash"] = true,
  ["hid"] = true,
  ["hints"] = true,
  ["host"] = true,
  ["hotkey"] = true,
  ["hsdocs"] = true,
  ["http"] = true,
  ["httpserver"] = true,
  ["image"] = true,
  ["inspect"] = true,
  ["ipc"] = true,
  ["itunes"] = true,
  ["javascript"] = true,
  ["json"] = true,
  ["keycodes"] = true,
  ["layout"] = true,
  ["location"] = true,
  ["logger"] = true,
  ["math"] = true,
  ["menubar"] = true,
  ["messages"] = true,
  ["midi"] = true,
  ["milight"] = true,
  ["mjomatic"] = true,
  ["mouse"] = true,
  ["network"] = true,
  ["noises"] = true,
  ["notify"] = true,
  ["osascript"] = true,
  ["pasteboard"] = true,
  ["pathwatcher"] = true,
  ["plist"] = true,
  ["razer"] = true,
  ["redshift"] = true,
  ["screen"] = true,
  ["serial"] = true,
  ["settings"] = true,
  ["sharing"] = true,
  ["shortcuts"] = true,
  ["socket"] = true,
  ["sound"] = true,
  ["spaces"] = true,
  ["speech"] = true,
  ["spoons"] = true,
  ["spotify"] = true,
  ["spotlight"] = true,
  ["sqlite3"] = true,
  ["streamdeck"] = true,
  ["styledtext"] = true,
  ["tabs"] = true,
  ["tangent"] = true,
  ["task"] = true,
  ["timer"] = true,
  ["uielement"] = true,
  ["urlevent"] = true,
  ["usb"] = true,
  ["utf8"] = true,
  ["vox"] = true,
  ["watchable"] = true,
  ["websocket"] = true,
  ["webview"] = true,
  ["wifi"] = true,
  ["window"] = true,
}

return M
